# Introduction {#intro}

A query using the word 'biogeochemistry' on NC State University libraries' website yielded 651 books on the subject in August 2018... So why having yet another one, or even a course on the subject...?! I suppose we are never done with a subject which is rather amorphous, as it involves many disciplines, and has many fields of application. 

Wikipedia [-@Wikipedia_contributors2018-fs] has some nice definitions of Biogeochemistry, including:

>In particular, biogeochemistry is the study of the cycles of chemical elements, such as carbon and nitrogen, and their interactions with and incorporation into living things transported through earth scale biological systems in space through time. 

With the definition above, the study of ancient earth history or of modern acid rains [e.g., @0080446426] are included in biogeochemistry... The unifying theme is that regardless of the application, the processes involved stay pretty much the same and involve *__transfer of electrons and protons__*. The differences within biogeochemistry come from the fields of application.

The field of application of this book is *__excess nutrient and sediment loads generated by human activities, their consequences on aquatic ecosystems, and the processes involved to improve and protect watershed and stream water quality__*. There is a niche in disturbed, nutrient rich, often rural environments, where we perceived there was a need for an integrated and horizontal delivery of knowledge spanning from electron orbitals, biochemistry, microbiology, hydrological functioning, process kinetic modeling, and treatment system design. It is possible that readers with strong biological background might find the biological facet of this book a bit short and simple. Just as well, non-engineers should not be afraid of 'engineering' in the title. The course is designed to provide the biological knowledge engineers might not have obtained in their curriculae, and the quantitative knowledge non-engineers might not have been exposed to. Regardless, I do hope that  environemental scientists, ecologists, and engineers alike, will find the integration of knowlege useful in this book.

The physical objects used as foundation for this class include naturally occurring and human-designed filters, which may reduce excess nutrient concentrations and loads in rural and suburban environments. Systems reviewed include wetlands, riparian buffers and vegetated filter strips, woodchip bioreactors, streams, stormwater ponds and bioretention zones. This book uses excess nitrogen as the core parameter where the principles of biogeochemical processes are well illustrated, and may apply to other fields of application. 


