<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 13 Introduction to hydrographs, chemographs, concentrations, and loads | Fundamental Hydro-Biogeochemistry for Ecological Engineering and Environmental Sciences</title>
  <meta name="description" content="Chapter 13 Introduction to hydrographs, chemographs, concentrations, and loads | Fundamental Hydro-Biogeochemistry for Ecological Engineering and Environmental Sciences" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 13 Introduction to hydrographs, chemographs, concentrations, and loads | Fundamental Hydro-Biogeochemistry for Ecological Engineering and Environmental Sciences" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 13 Introduction to hydrographs, chemographs, concentrations, and loads | Fundamental Hydro-Biogeochemistry for Ecological Engineering and Environmental Sciences" />
  
  
  

<meta name="author" content="François Birgand" />


<meta name="date" content="2022-02-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="gassolubilitychapter.html"/>
<link rel="next" href="glossary.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="toc.css" type="text/css" />
<link rel="stylesheet" href="font-awesome.min.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Textbook for BAE 587</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#author"><i class="fa fa-check"></i>Author</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#biogeochemistry-applied-to-excess-nutrients-in-rural-aquatic-environments"><i class="fa fa-check"></i><b>1.1</b> Biogeochemistry applied to excess nutrients in rural aquatic environments</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#ecologically-engineered-systems-treated-as-black-boxes"><i class="fa fa-check"></i><b>1.2</b> Ecologically engineered systems treated as black boxes</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#biogeochemical-processes-in-pollution-flows"><i class="fa fa-check"></i><b>1.3</b> Biogeochemical processes in pollution flows</a></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#scope-of-this-book"><i class="fa fa-check"></i><b>1.4</b> Scope of this book</a></li>
<li class="chapter" data-level="1.5" data-path="intro.html"><a href="intro.html#exercises"><i class="fa fa-check"></i><b>1.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="electron-allocation.html"><a href="electron-allocation.html"><i class="fa fa-check"></i><b>2</b> Life’s secrets for storing energy</a><ul>
<li class="chapter" data-level="2.1" data-path="electron-allocation.html"><a href="electron-allocation.html#the-five-fundamental-requirements-of-life"><i class="fa fa-check"></i><b>2.1</b> The five fundamental requirements of life</a></li>
<li class="chapter" data-level="2.2" data-path="electron-allocation.html"><a href="electron-allocation.html#electron-allocation-onto-chonsp"><i class="fa fa-check"></i><b>2.2</b> Electron allocation onto CHONSP</a></li>
<li class="chapter" data-level="2.3" data-path="electron-allocation.html"><a href="electron-allocation.html#electronegativity-as-a-powerful-tool-to-allocate-electrons"><i class="fa fa-check"></i><b>2.3</b> Electronegativity as a powerful tool to allocate electrons</a></li>
<li class="chapter" data-level="2.4" data-path="electron-allocation.html"><a href="electron-allocation.html#dioxygen-the-electron-kleptomaniac-molecule"><i class="fa fa-check"></i><b>2.4</b> Dioxygen: the ‘electron kleptomaniac’ molecule</a></li>
<li class="chapter" data-level="2.5" data-path="electron-allocation.html"><a href="electron-allocation.html#fully-oxidized-forms-of-cnsp"><i class="fa fa-check"></i><b>2.5</b> Fully Oxidized forms of CNSP</a></li>
<li class="chapter" data-level="2.6" data-path="electron-allocation.html"><a href="electron-allocation.html#oxidation-versus-reduction"><i class="fa fa-check"></i><b>2.6</b> Oxidation versus Reduction</a></li>
<li class="chapter" data-level="2.7" data-path="electron-allocation.html"><a href="electron-allocation.html#a-gradient-of-oxidation-and-reduction-states-on-inorganic-and-organic-molecules"><i class="fa fa-check"></i><b>2.7</b> A gradient of oxidation and reduction states on inorganic and organic molecules</a></li>
<li class="chapter" data-level="2.8" data-path="electron-allocation.html"><a href="electron-allocation.html#examples-of-electrons-stored-on-organic-molecules"><i class="fa fa-check"></i><b>2.8</b> Examples of electrons stored on organic molecules</a></li>
<li class="chapter" data-level="2.9" data-path="electron-allocation.html"><a href="electron-allocation.html#summary-on-electron-allocations"><i class="fa fa-check"></i><b>2.9</b> Summary on electron allocations</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="functional-groups.html"><a href="functional-groups.html"><i class="fa fa-check"></i><b>3</b> Functional groups of biochemical importance</a><ul>
<li class="chapter" data-level="3.1" data-path="functional-groups.html"><a href="functional-groups.html#hydrocarbon-chains"><i class="fa fa-check"></i><b>3.1</b> Hydrocarbon chains</a><ul>
<li class="chapter" data-level="3.1.1" data-path="functional-groups.html"><a href="functional-groups.html#alkanes"><i class="fa fa-check"></i><b>3.1.1</b> Alkanes</a></li>
<li class="chapter" data-level="3.1.2" data-path="functional-groups.html"><a href="functional-groups.html#unsaturated-hydrocarbons"><i class="fa fa-check"></i><b>3.1.2</b> Unsaturated hydrocarbons</a></li>
<li class="chapter" data-level="3.1.3" data-path="functional-groups.html"><a href="functional-groups.html#aromatics"><i class="fa fa-check"></i><b>3.1.3</b> Aromatic hydrocarbons</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="functional-groups.html"><a href="functional-groups.html#functional-groups-from-alkane-chain-oxidation"><i class="fa fa-check"></i><b>3.2</b> Functional groups from alkane chain oxidation</a><ul>
<li class="chapter" data-level="3.2.1" data-path="functional-groups.html"><a href="functional-groups.html#hydroxyl-and-sulfanyl-functional-groups"><i class="fa fa-check"></i><b>3.2.1</b> Hydroxyl and sulfanyl functional groups</a></li>
<li class="chapter" data-level="3.2.2" data-path="functional-groups.html"><a href="functional-groups.html#amines"><i class="fa fa-check"></i><b>3.2.2</b> Amine functional group</a></li>
<li class="chapter" data-level="3.2.3" data-path="functional-groups.html"><a href="functional-groups.html#carbonyl-and-acyl-functional-groups"><i class="fa fa-check"></i><b>3.2.3</b> Carbonyl and acyl functional groups</a></li>
<li class="chapter" data-level="3.2.4" data-path="functional-groups.html"><a href="functional-groups.html#alcohols"><i class="fa fa-check"></i><b>3.2.4</b> Alcohol functional group</a></li>
<li class="chapter" data-level="3.2.5" data-path="functional-groups.html"><a href="functional-groups.html#thiols"><i class="fa fa-check"></i><b>3.2.5</b> Thiol functional group</a></li>
<li class="chapter" data-level="3.2.6" data-path="functional-groups.html"><a href="functional-groups.html#alkyl-amines"><i class="fa fa-check"></i><b>3.2.6</b> Alkyl amines</a></li>
<li class="chapter" data-level="3.2.7" data-path="functional-groups.html"><a href="functional-groups.html#aldehyde"><i class="fa fa-check"></i><b>3.2.7</b> Aldehyde functional group</a></li>
<li class="chapter" data-level="3.2.8" data-path="functional-groups.html"><a href="functional-groups.html#ketone"><i class="fa fa-check"></i><b>3.2.8</b> Ketone functional group</a></li>
<li class="chapter" data-level="3.2.9" data-path="functional-groups.html"><a href="functional-groups.html#carboxyl-functional-group"><i class="fa fa-check"></i><b>3.2.9</b> Carboxyl functional group</a></li>
<li class="chapter" data-level="3.2.10" data-path="functional-groups.html"><a href="functional-groups.html#amides"><i class="fa fa-check"></i><b>3.2.10</b> Amide functional group</a></li>
<li class="chapter" data-level="3.2.11" data-path="functional-groups.html"><a href="functional-groups.html#methoxy"><i class="fa fa-check"></i><b>3.2.11</b> Methoxy functional group</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="functional-groups.html"><a href="functional-groups.html#functional-groups-from-bonding-of-functionalized-organic-molecules"><i class="fa fa-check"></i><b>3.3</b> Functional groups from bonding of functionalized organic molecules</a><ul>
<li class="chapter" data-level="3.3.1" data-path="functional-groups.html"><a href="functional-groups.html#ester-functional-group"><i class="fa fa-check"></i><b>3.3.1</b> Ester functional group</a></li>
<li class="chapter" data-level="3.3.2" data-path="functional-groups.html"><a href="functional-groups.html#thioesters"><i class="fa fa-check"></i><b>3.3.2</b> Thioesters</a></li>
<li class="chapter" data-level="3.3.3" data-path="functional-groups.html"><a href="functional-groups.html#phosphoesters"><i class="fa fa-check"></i><b>3.3.3</b> Phosphoesters</a></li>
<li class="chapter" data-level="3.3.4" data-path="functional-groups.html"><a href="functional-groups.html#ether"><i class="fa fa-check"></i><b>3.3.4</b> Ether functional group</a></li>
<li class="chapter" data-level="3.3.5" data-path="functional-groups.html"><a href="functional-groups.html#disulfide"><i class="fa fa-check"></i><b>3.3.5</b> Disulfide functional groups</a></li>
<li class="chapter" data-level="3.3.6" data-path="functional-groups.html"><a href="functional-groups.html#hemiacetal"><i class="fa fa-check"></i><b>3.3.6</b> Hemiacetal and hemiketal functional groups</a></li>
<li class="chapter" data-level="3.3.7" data-path="functional-groups.html"><a href="functional-groups.html#anyhydride"><i class="fa fa-check"></i><b>3.3.7</b> Anhydride and phosphoanhydride functional groups</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="functional-groups.html"><a href="functional-groups.html#commonmolecules"><i class="fa fa-check"></i><b>3.4</b> Summary on functional groups and important radicals</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="molecular-families.html"><a href="molecular-families.html"><i class="fa fa-check"></i><b>4</b> Life’s secrets to make complex organic molecules</a><ul>
<li class="chapter" data-level="4.1" data-path="molecular-families.html"><a href="molecular-families.html#polymers-of-simple-monomers"><i class="fa fa-check"></i><b>4.1</b> Polymers of simple monomers</a></li>
<li class="chapter" data-level="4.2" data-path="molecular-families.html"><a href="molecular-families.html#carbohydrates"><i class="fa fa-check"></i><b>4.2</b> Carbohydrates</a><ul>
<li class="chapter" data-level="4.2.1" data-path="molecular-families.html"><a href="molecular-families.html#Monosaccharides"><i class="fa fa-check"></i><b>4.2.1</b> Monosaccharides</a></li>
<li class="chapter" data-level="4.2.2" data-path="molecular-families.html"><a href="molecular-families.html#dissacharides"><i class="fa fa-check"></i><b>4.2.2</b> Dissacharides</a></li>
<li class="chapter" data-level="4.2.3" data-path="molecular-families.html"><a href="molecular-families.html#polyssaccharides-or-glycans"><i class="fa fa-check"></i><b>4.2.3</b> Polyssaccharides or glycans</a></li>
<li class="chapter" data-level="4.2.4" data-path="molecular-families.html"><a href="molecular-families.html#other-important-carbohydrates"><i class="fa fa-check"></i><b>4.2.4</b> Other important carbohydrates</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="molecular-families.html"><a href="molecular-families.html#proteins"><i class="fa fa-check"></i><b>4.3</b> Proteins</a></li>
<li class="chapter" data-level="4.4" data-path="molecular-families.html"><a href="molecular-families.html#nucleic-acids"><i class="fa fa-check"></i><b>4.4</b> Nucleic Acids and Nucleotides</a><ul>
<li class="chapter" data-level="4.4.1" data-path="molecular-families.html"><a href="molecular-families.html#nucleotides-as-monomers-of-nucleic-acids"><i class="fa fa-check"></i><b>4.4.1</b> Nucleotides as monomers of nucleic acids</a></li>
<li class="chapter" data-level="4.4.2" data-path="molecular-families.html"><a href="molecular-families.html#dna-and-rna"><i class="fa fa-check"></i><b>4.4.2</b> DNA and RNA</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="molecular-families.html"><a href="molecular-families.html#lipids"><i class="fa fa-check"></i><b>4.5</b> Lipids</a><ul>
<li class="chapter" data-level="4.5.1" data-path="molecular-families.html"><a href="molecular-families.html#overview-of-fatty-acid--or-acyl-based-lipids"><i class="fa fa-check"></i><b>4.5.1</b> Overview of fatty acid- or acyl-based lipids</a></li>
<li class="chapter" data-level="4.5.2" data-path="molecular-families.html"><a href="molecular-families.html#membrane-lipids"><i class="fa fa-check"></i><b>4.5.2</b> Lipids as key to cell membrane structure and function</a></li>
<li class="chapter" data-level="4.5.3" data-path="molecular-families.html"><a href="molecular-families.html#fatty-acids"><i class="fa fa-check"></i><b>4.5.3</b> Fatty acids: lipids of their own and primary common building blocks</a></li>
<li class="chapter" data-level="4.5.4" data-path="molecular-families.html"><a href="molecular-families.html#glycerolipids-for-energy-storage"><i class="fa fa-check"></i><b>4.5.4</b> Glycerolipids for energy storage</a></li>
<li class="chapter" data-level="4.5.5" data-path="molecular-families.html"><a href="molecular-families.html#glycerophospholipids-or-phospholipids-for-cell-membranes"><i class="fa fa-check"></i><b>4.5.5</b> Glycerophospholipids or phospholipids for cell membranes</a></li>
<li class="chapter" data-level="4.5.6" data-path="molecular-families.html"><a href="molecular-families.html#sphingolipids"><i class="fa fa-check"></i><b>4.5.6</b> Sphingolipids use sphingosine as backbone/fatty acid</a></li>
<li class="chapter" data-level="4.5.7" data-path="molecular-families.html"><a href="molecular-families.html#saccharolipids-in-bacterial-membranes"><i class="fa fa-check"></i><b>4.5.7</b> Saccharolipids in bacterial membranes</a></li>
<li class="chapter" data-level="4.5.8" data-path="molecular-families.html"><a href="molecular-families.html#summary-about-the-acyl-based-lipids"><i class="fa fa-check"></i><b>4.5.8</b> Summary about the acyl-based-lipids</a></li>
<li class="chapter" data-level="4.5.9" data-path="molecular-families.html"><a href="molecular-families.html#overview-of-the-isoprene-based-lipids"><i class="fa fa-check"></i><b>4.5.9</b> Overview of the isoprene-based lipids</a></li>
<li class="chapter" data-level="4.5.10" data-path="molecular-families.html"><a href="molecular-families.html#isoprenoids"><i class="fa fa-check"></i><b>4.5.10</b> Prenol or isoprenoid lipids</a></li>
<li class="chapter" data-level="4.5.11" data-path="molecular-families.html"><a href="molecular-families.html#sterols"><i class="fa fa-check"></i><b>4.5.11</b> Sterol lipids</a></li>
<li class="chapter" data-level="4.5.12" data-path="molecular-families.html"><a href="molecular-families.html#summary-about-the-isoprene-based-lipids"><i class="fa fa-check"></i><b>4.5.12</b> Summary about the isoprene-based lipids</a></li>
<li class="chapter" data-level="4.5.13" data-path="molecular-families.html"><a href="molecular-families.html#other-notable-lipids"><i class="fa fa-check"></i><b>4.5.13</b> Other notable lipids</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="molecular-families.html"><a href="molecular-families.html#phenolics"><i class="fa fa-check"></i><b>4.6</b> Phenolics and polyphenols</a><ul>
<li class="chapter" data-level="4.6.1" data-path="molecular-families.html"><a href="molecular-families.html#the-impermeable-world-of-phenolics"><i class="fa fa-check"></i><b>4.6.1</b> The impermeable world of phenolics</a></li>
<li class="chapter" data-level="4.6.2" data-path="molecular-families.html"><a href="molecular-families.html#unavailable-energy-onto-phenolic-molecules"><i class="fa fa-check"></i><b>4.6.2</b> Unavailable energy onto phenolic molecules</a></li>
<li class="chapter" data-level="4.6.3" data-path="molecular-families.html"><a href="molecular-families.html#monomeric-phenols"><i class="fa fa-check"></i><b>4.6.3</b> Monomeric phenols</a></li>
<li class="chapter" data-level="4.6.4" data-path="molecular-families.html"><a href="molecular-families.html#lignins"><i class="fa fa-check"></i><b>4.6.4</b> Lignins</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="molecular-families.html"><a href="molecular-families.html#alkaloids"><i class="fa fa-check"></i><b>4.7</b> Alkaloids</a></li>
<li class="chapter" data-level="4.8" data-path="molecular-families.html"><a href="molecular-families.html#glucosinolates"><i class="fa fa-check"></i><b>4.8</b> Glucosinolates</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html"><i class="fa fa-check"></i><b>5</b> Energy generation and aerobic respiration</a><ul>
<li class="chapter" data-level="5.1" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html#generating-energy-transfer-of-electrons"><i class="fa fa-check"></i><b>5.1</b> Generating energy: transfer of electrons</a><ul>
<li class="chapter" data-level="5.1.1" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html#activation-energy-barrier"><i class="fa fa-check"></i><b>5.1.1</b> Activation energy barrier</a></li>
<li class="chapter" data-level="5.1.2" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html#methane-combustion"><i class="fa fa-check"></i><b>5.1.2</b> Electron transfer during methane combustion</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html#ATP"><i class="fa fa-check"></i><b>5.2</b> Generating energy without combustion: ATP or the energy currency of the cell</a></li>
<li class="chapter" data-level="5.3" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html#the-atp-manufacture-substrate-level-versus-oxidative-phosphorylation"><i class="fa fa-check"></i><b>5.3</b> The ATP manufacture: substrate-level versus oxidative phosphorylation</a></li>
<li class="chapter" data-level="5.4" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html#respiration"><i class="fa fa-check"></i><b>5.4</b> Respiration: providing most ATP thanks to exogenous electron acceptors and oxidative phosphorylation</a><ul>
<li class="chapter" data-level="5.4.1" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html#oxidative-phosphorylation-through-molecular-mechanical-forces"><i class="fa fa-check"></i><b>5.4.1</b> Oxidative phosphorylation through molecular mechanical forces</a></li>
<li class="chapter" data-level="5.4.2" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html#creating-a-proton-gradient-as-a-source-of-proton-flow"><i class="fa fa-check"></i><b>5.4.2</b> Creating a proton gradient as a source of proton flow</a></li>
<li class="chapter" data-level="5.4.3" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html#a-compartment-to-accumulate-protons"><i class="fa fa-check"></i><b>5.4.3</b> A compartment to accumulate protons</a></li>
<li class="chapter" data-level="5.4.4" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html#proton-pumping"><i class="fa fa-check"></i><b>5.4.4</b> A supply of protons for the intermembrane space: proton pumps</a></li>
<li class="chapter" data-level="5.4.5" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html#NADFAD"><i class="fa fa-check"></i><b>5.4.5</b> Electron transfer molecules that power the proton pumps</a></li>
<li class="chapter" data-level="5.4.6" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html#transfer-of-electrons-from-the-organic-carbon-to-an-electron-acceptor"><i class="fa fa-check"></i><b>5.4.6</b> Transfer of electrons from the Organic Carbon to an electron acceptor</a></li>
<li class="chapter" data-level="5.4.7" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html#oxidativephosphorylation"><i class="fa fa-check"></i><b>5.4.7</b> Oxygen reduction and oxidative phosphorylation</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html#respiration-electron-flow-schemes"><i class="fa fa-check"></i><b>5.5</b> Respiration electron flow schemes</a><ul>
<li class="chapter" data-level="5.5.1" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html#organotrophic-aerobic-respiration"><i class="fa fa-check"></i><b>5.5.1</b> Aerobic respiration schemes for organotrophs</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html#glycolysis"><i class="fa fa-check"></i><b>5.6</b> Glycolysis: an ancient way to produce ATP from glucose by substrate-level phosphorylation</a><ul>
<li class="chapter" data-level="5.6.1" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html#substrate-level-phosphorylation"><i class="fa fa-check"></i><b>5.6.1</b> Substrate-level phosphorylation</a></li>
<li class="chapter" data-level="5.6.2" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html#energy-investment-and-energy-pay-off-phases-of-glycolysis"><i class="fa fa-check"></i><b>5.6.2</b> Energy investment and energy pay off phases of glycolysis</a></li>
<li class="chapter" data-level="5.6.3" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html#electrons-fate-and-electron-transfer-molecules"><i class="fa fa-check"></i><b>5.6.3</b> Electrons fate and electron transfer molecules</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html#the-citric-acid-or-krebs-cycle-as-an-efficient-way-to-transfer-high-energy-electrons"><i class="fa fa-check"></i><b>5.7</b> The citric acid or Krebs cycle as an efficient way to transfer high energy electrons</a><ul>
<li class="chapter" data-level="5.7.1" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html#oxidation-of-pyruvate-as-a-preliminary-step"><i class="fa fa-check"></i><b>5.7.1</b> Oxidation of pyruvate as a preliminary step</a></li>
<li class="chapter" data-level="5.7.2" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html#transfer-of-all-electrons-to-nad-and-fad"><i class="fa fa-check"></i><b>5.7.2</b> Transfer of all electrons to NAD<sup>+</sup> and FAD</a></li>
<li class="chapter" data-level="5.7.3" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html#summary-of-respiration"><i class="fa fa-check"></i><b>5.7.3</b> Summary of respiration</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="aerobic-and-anaerobic-respiration.html"><a href="aerobic-and-anaerobic-respiration.html#fermentation-or-staying-alive-without-exogenous-electron-acceptor"><i class="fa fa-check"></i><b>5.8</b> Fermentation or staying alive without exogenous electron acceptor</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="photosynthesis.html"><a href="photosynthesis.html"><i class="fa fa-check"></i><b>6</b> Capturing and storing energy: photosynthesis</a><ul>
<li class="chapter" data-level="6.1" data-path="photosynthesis.html"><a href="photosynthesis.html#requirements-to-store-energy-on-organic-molecules"><i class="fa fa-check"></i><b>6.1</b> Requirements to store energy on organic molecules</a></li>
<li class="chapter" data-level="6.2" data-path="photosynthesis.html"><a href="photosynthesis.html#no-need-to-reinvent-the-wheel-for-the-production-of-atp-and-the-transfer-of-electrons"><i class="fa fa-check"></i><b>6.2</b> No need to reinvent the wheel for the production of ATP and the transfer of electrons</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="redoxwetland.html"><a href="redoxwetland.html"><i class="fa fa-check"></i><b>7</b> The classical collection of electron donors and acceptors</a><ul>
<li class="chapter" data-level="7.1" data-path="redoxwetland.html"><a href="redoxwetland.html#the-theoretical-vertical-sequence-of-respiratory-processes-in-wetland-soils"><i class="fa fa-check"></i><b>7.1</b> The theoretical vertical sequence of respiratory processes in wetland soils</a></li>
<li class="chapter" data-level="7.2" data-path="redoxwetland.html"><a href="redoxwetland.html#aerobiczone"><i class="fa fa-check"></i><b>7.2</b> An aerobic layer near the soil-water interface</a><ul>
<li class="chapter" data-level="7.2.1" data-path="redoxwetland.html"><a href="redoxwetland.html#oxygen-supply-and-demand-at-the-sediment-water-interface"><i class="fa fa-check"></i><b>7.2.1</b> Oxygen supply and demand at the sediment water interface</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="redoxwetland.html"><a href="redoxwetland.html#respiration-in-the-anaerobic-zone-of-the-soil"><i class="fa fa-check"></i><b>7.3</b> Respiration in the anaerobic zone of the soil</a></li>
<li class="chapter" data-level="7.4" data-path="redoxwetland.html"><a href="redoxwetland.html#denit"><i class="fa fa-check"></i><b>7.4</b> A denitrification layer below the aerobic layer</a></li>
<li class="chapter" data-level="7.5" data-path="redoxwetland.html"><a href="redoxwetland.html#manganese-and-iron-oxides-reductions"><i class="fa fa-check"></i><b>7.5</b> Manganese and Iron oxides reductions</a></li>
<li class="chapter" data-level="7.6" data-path="redoxwetland.html"><a href="redoxwetland.html#sulfate-reduction"><i class="fa fa-check"></i><b>7.6</b> Sulfate reduction</a></li>
<li class="chapter" data-level="7.7" data-path="redoxwetland.html"><a href="redoxwetland.html#the-methanogenesis-oddity"><i class="fa fa-check"></i><b>7.7</b> The methanogenesis oddity</a></li>
<li class="chapter" data-level="7.8" data-path="redoxwetland.html"><a href="redoxwetland.html#fermentation-in-wetland-and-stream-sediment"><i class="fa fa-check"></i><b>7.8</b> Fermentation in wetland and stream sediment</a></li>
<li class="chapter" data-level="7.9" data-path="redoxwetland.html"><a href="redoxwetland.html#first-summary-on-the-electron-acceptor-chain-in-wetland-soils"><i class="fa fa-check"></i><b>7.9</b> First summary on the electron acceptor chain in wetland soils</a></li>
<li class="chapter" data-level="7.10" data-path="redoxwetland.html"><a href="redoxwetland.html#supply-and-demand-of-electron-acceptors-and-of-the-byproducts-of-organic-matter-oxidation"><i class="fa fa-check"></i><b>7.10</b> Supply and demand of electron acceptors and of the byproducts of Organic Matter oxidation</a><ul>
<li class="chapter" data-level="7.10.1" data-path="redoxwetland.html"><a href="redoxwetland.html#demands-drive-downward-fluxes-of-dioxygen-nitrate-and-sulfate"><i class="fa fa-check"></i><b>7.10.1</b> Demands drive downward fluxes of dioxygen, nitrate and sulfate</a></li>
<li class="chapter" data-level="7.10.2" data-path="redoxwetland.html"><a href="redoxwetland.html#supply-of-byproducts-of-organic-matter-oxidation"><i class="fa fa-check"></i><b>7.10.2</b> Supply of byproducts of organic matter oxidation</a></li>
<li class="chapter" data-level="7.10.3" data-path="redoxwetland.html"><a href="redoxwetland.html#nitrification"><i class="fa fa-check"></i><b>7.10.3</b> Nitrification</a></li>
<li class="chapter" data-level="7.10.4" data-path="redoxwetland.html"><a href="redoxwetland.html#gas-bubble-formation"><i class="fa fa-check"></i><b>7.10.4</b> Gas bubble formation</a></li>
<li class="chapter" data-level="7.10.5" data-path="redoxwetland.html"><a href="redoxwetland.html#oxidation-of-upward-moving-reduced-sulfur"><i class="fa fa-check"></i><b>7.10.5</b> Oxidation of upward moving reduced sulfur</a></li>
<li class="chapter" data-level="7.10.6" data-path="redoxwetland.html"><a href="redoxwetland.html#oxidation-of-upward-moving-mn2-and-fe2"><i class="fa fa-check"></i><b>7.10.6</b> Oxidation of upward moving <span class="math inline">\(Mn^{2+}\)</span> and <span class="math inline">\(Fe^{2+}\)</span></a></li>
<li class="chapter" data-level="7.10.7" data-path="redoxwetland.html"><a href="redoxwetland.html#moving-of-dissolved-organic-carbon"><i class="fa fa-check"></i><b>7.10.7</b> Moving of Dissolved Organic Carbon</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="unclassicalredox.html"><a href="unclassicalredox.html"><i class="fa fa-check"></i><b>8</b> The not so classical electron donors and acceptors</a><ul>
<li class="chapter" data-level="8.1" data-path="unclassicalredox.html"><a href="unclassicalredox.html#dnra"><i class="fa fa-check"></i><b>8.1</b> DNRA</a></li>
<li class="chapter" data-level="8.2" data-path="unclassicalredox.html"><a href="unclassicalredox.html#anammox"><i class="fa fa-check"></i><b>8.2</b> Anammox</a></li>
<li class="chapter" data-level="8.3" data-path="unclassicalredox.html"><a href="unclassicalredox.html#nitrification-denitrification"><i class="fa fa-check"></i><b>8.3</b> Nitrification-denitrification</a></li>
<li class="chapter" data-level="8.4" data-path="unclassicalredox.html"><a href="unclassicalredox.html#chemilithotrophic-denitrification"><i class="fa fa-check"></i><b>8.4</b> Chemilithotrophic denitrification</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="conc-levels.html"><a href="conc-levels.html"><i class="fa fa-check"></i><b>9</b> Nutrient concentration levels in rural and suburban environments</a><ul>
<li class="chapter" data-level="9.1" data-path="conc-levels.html"><a href="conc-levels.html#level-of-dissolved-oxygen-concentrations-in-open-waters"><i class="fa fa-check"></i><b>9.1</b> Level of dissolved oxygen concentrations in open waters</a><ul>
<li class="chapter" data-level="9.1.1" data-path="conc-levels.html"><a href="conc-levels.html#the-supply-and-demand-of-o2-in-water"><i class="fa fa-check"></i><b>9.1.1</b> The supply and demand of O<sub>2</sub> in water</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="conc-levels.html"><a href="conc-levels.html#level-of-nutrient-concentrations-in-natural-undisturbed-streams"><i class="fa fa-check"></i><b>9.2</b> Level of nutrient concentrations in natural undisturbed streams</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="acidbase.html"><a href="acidbase.html"><i class="fa fa-check"></i><b>10</b> Applied thermochemistry: acid-base equilibria</a><ul>
<li class="chapter" data-level="10.1" data-path="acidbase.html"><a href="acidbase.html#the-brønstedlowry-acidbase-theory"><i class="fa fa-check"></i><b>10.1</b> The Brønsted–Lowry acid–base theory</a></li>
<li class="chapter" data-level="10.2" data-path="acidbase.html"><a href="acidbase.html#acid-base-equilibrium-parameters"><i class="fa fa-check"></i><b>10.2</b> Acid-base equilibrium parameters</a><ul>
<li class="chapter" data-level="10.2.1" data-path="acidbase.html"><a href="acidbase.html#ka"><i class="fa fa-check"></i><b>10.2.1</b> K<sub>A</sub></a></li>
<li class="chapter" data-level="10.2.2" data-path="acidbase.html"><a href="acidbase.html#pka"><i class="fa fa-check"></i><b>10.2.2</b> pK<sub>A</sub></a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="acidbase.html"><a href="acidbase.html#self-ionization-of-water"><i class="fa fa-check"></i><b>10.3</b> Self-ionization of water</a></li>
<li class="chapter" data-level="10.4" data-path="acidbase.html"><a href="acidbase.html#strong-vs.weak-acids"><i class="fa fa-check"></i><b>10.4</b> Strong vs. weak acids</a></li>
<li class="chapter" data-level="10.5" data-path="acidbase.html"><a href="acidbase.html#mono--and-polyprotic-acids-mole-fractions"><i class="fa fa-check"></i><b>10.5</b> Mono- and polyprotic acids mole fractions</a><ul>
<li class="chapter" data-level="10.5.1" data-path="acidbase.html"><a href="acidbase.html#triprotic-acid-example"><i class="fa fa-check"></i><b>10.5.1</b> Triprotic acid example</a></li>
<li class="chapter" data-level="10.5.2" data-path="acidbase.html"><a href="acidbase.html#generalized-polyprotic-acid-mole-fractions"><i class="fa fa-check"></i><b>10.5.2</b> Generalized polyprotic acid mole fractions</a></li>
<li class="chapter" data-level="10.5.3" data-path="acidbase.html"><a href="acidbase.html#graphical-illustration-of-mole-fractions-of-ecologically-relevant-weak-acids"><i class="fa fa-check"></i><b>10.5.3</b> Graphical illustration of mole fractions of ecologically relevant weak acids</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="acidbase.html"><a href="acidbase.html#equilibrium-calculations-using-a-graphical-method"><i class="fa fa-check"></i><b>10.6</b> Equilibrium calculations using a graphical method</a><ul>
<li class="chapter" data-level="10.6.1" data-path="acidbase.html"><a href="acidbase.html#logarithm-of-concentrations-as-a-function-of-ph"><i class="fa fa-check"></i><b>10.6.1</b> Logarithm of concentrations as a function of pH</a></li>
<li class="chapter" data-level="10.6.2" data-path="acidbase.html"><a href="acidbase.html#logConcMonoAcid"><i class="fa fa-check"></i><b>10.6.2</b> Graphical approach to calculate pH for a monoprotic acid</a></li>
<li class="chapter" data-level="10.6.3" data-path="acidbase.html"><a href="acidbase.html#logConcTriAcid"><i class="fa fa-check"></i><b>10.6.3</b> Graphical approach to calculate pH for a triprotic acid</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="redox.html"><a href="redox.html"><i class="fa fa-check"></i><b>11</b> Applied thermochemistry: Oxido-Reduction equilibria</a><ul>
<li class="chapter" data-level="11.0.1" data-path="redox.html"><a href="redox.html#some-outside-the-box-redox-reactions"><i class="fa fa-check"></i><b>11.0.1</b> Some outside the box redox reactions</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="gassolubilitychapter.html"><a href="gassolubilitychapter.html"><i class="fa fa-check"></i><b>12</b> Dissolved gases in water</a><ul>
<li class="chapter" data-level="12.1" data-path="gassolubilitychapter.html"><a href="gassolubilitychapter.html#henrys-law-and-the-dissolution-of-gases-in-water"><i class="fa fa-check"></i><b>12.1</b> Henry’s law and the dissolution of gases in water</a><ul>
<li class="chapter" data-level="12.1.1" data-path="gassolubilitychapter.html"><a href="gassolubilitychapter.html#equivalence-between-gas-partial-pressures-and-dissolved-concentration"><i class="fa fa-check"></i><b>12.1.1</b> Equivalence between gas partial pressures and dissolved concentration</a></li>
<li class="chapter" data-level="12.1.2" data-path="gassolubilitychapter.html"><a href="gassolubilitychapter.html#many-different-units-to-express-gas-solubility"><i class="fa fa-check"></i><b>12.1.2</b> Many different units to express gas solubility</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="gassolubilitychapter.html"><a href="gassolubilitychapter.html#solubility-of-gases-as-a-function-of-temperature"><i class="fa fa-check"></i><b>12.2</b> Solubility of gases as a function of temperature</a></li>
<li class="chapter" data-level="12.3" data-path="gassolubilitychapter.html"><a href="gassolubilitychapter.html#actual-solubility-values-of-water-in-equilibrium-with-the-atmosphere"><i class="fa fa-check"></i><b>12.3</b> Actual solubility values of water in equilibrium with the atmosphere</a></li>
<li class="chapter" data-level="12.4" data-path="gassolubilitychapter.html"><a href="gassolubilitychapter.html#solubility-of-gases-as-a-function-of-pressure"><i class="fa fa-check"></i><b>12.4</b> Solubility of gases as a function of pressure</a><ul>
<li class="chapter" data-level="12.4.1" data-path="gassolubilitychapter.html"><a href="gassolubilitychapter.html#daltons-law-of-partial-pressures"><i class="fa fa-check"></i><b>12.4.1</b> Dalton’s law of partial pressures</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="introduction-to-hydrographs-chemographs-concentrations-and-loads.html"><a href="introduction-to-hydrographs-chemographs-concentrations-and-loads.html"><i class="fa fa-check"></i><b>13</b> Introduction to hydrographs, chemographs, concentrations, and loads</a><ul>
<li class="chapter" data-level="13.1" data-path="introduction-to-hydrographs-chemographs-concentrations-and-loads.html"><a href="introduction-to-hydrographs-chemographs-concentrations-and-loads.html#hydrographs-as-the-basic-hydrologist-tool"><i class="fa fa-check"></i><b>13.1</b> Hydrographs as the basic hydrologist tool</a><ul>
<li class="chapter" data-level="13.1.1" data-path="introduction-to-hydrographs-chemographs-concentrations-and-loads.html"><a href="introduction-to-hydrographs-chemographs-concentrations-and-loads.html#characteristics-of-a-hydrograph"><i class="fa fa-check"></i><b>13.1.1</b> Characteristics of a hydrograph</a></li>
<li class="chapter" data-level="13.1.2" data-path="introduction-to-hydrographs-chemographs-concentrations-and-loads.html"><a href="introduction-to-hydrographs-chemographs-concentrations-and-loads.html#actual-hydrograph-over-an-entire-year"><i class="fa fa-check"></i><b>13.1.2</b> Actual hydrograph over an entire year</a></li>
<li class="chapter" data-level="13.1.3" data-path="introduction-to-hydrographs-chemographs-concentrations-and-loads.html"><a href="introduction-to-hydrographs-chemographs-concentrations-and-loads.html#calculating-water-fluxes-or-cumulative-flow-volumes"><i class="fa fa-check"></i><b>13.1.3</b> Calculating water fluxes or cumulative flow volumes</a></li>
<li class="chapter" data-level="13.1.4" data-path="introduction-to-hydrographs-chemographs-concentrations-and-loads.html"><a href="introduction-to-hydrographs-chemographs-concentrations-and-loads.html#evaluating-the-importance-of-rare-high-flow-events-flow-duration-curves"><i class="fa fa-check"></i><b>13.1.4</b> Evaluating the importance of rare high flow events: flow duration curves</a></li>
<li class="chapter" data-level="13.1.5" data-path="introduction-to-hydrographs-chemographs-concentrations-and-loads.html"><a href="introduction-to-hydrographs-chemographs-concentrations-and-loads.html#flow-duration-curves-as-flow-exceedance-curves"><i class="fa fa-check"></i><b>13.1.5</b> Flow duration curves as flow exceedance curves</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="introduction-to-hydrographs-chemographs-concentrations-and-loads.html"><a href="introduction-to-hydrographs-chemographs-concentrations-and-loads.html#chemographs-and-concentration-levels"><i class="fa fa-check"></i><b>13.2</b> Chemographs and concentration levels</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="glossary.html"><a href="glossary.html"><i class="fa fa-check"></i><b>14</b> Glossary</a><ul>
<li class="chapter" data-level="14.1" data-path="glossary.html"><a href="glossary.html#a"><i class="fa fa-check"></i><b>14.1</b> A</a><ul>
<li class="chapter" data-level="14.1.1" data-path="glossary.html"><a href="glossary.html#aerobic-respiration"><i class="fa fa-check"></i><b>14.1.1</b> Aerobic respiration</a></li>
<li class="chapter" data-level="14.1.2" data-path="glossary.html"><a href="glossary.html#anaerobic-respiration"><i class="fa fa-check"></i><b>14.1.2</b> Anaerobic respiration</a></li>
<li class="chapter" data-level="14.1.3" data-path="glossary.html"><a href="glossary.html#ammonia"><i class="fa fa-check"></i><b>14.1.3</b> Ammonia</a></li>
<li class="chapter" data-level="14.1.4" data-path="glossary.html"><a href="glossary.html#ammonium"><i class="fa fa-check"></i><b>14.1.4</b> Ammonium</a></li>
<li class="chapter" data-level="14.1.5" data-path="glossary.html"><a href="glossary.html#ammonium-nitrate"><i class="fa fa-check"></i><b>14.1.5</b> Ammonium nitrate</a></li>
<li class="chapter" data-level="14.1.6" data-path="glossary.html"><a href="glossary.html#anoxic-waters"><i class="fa fa-check"></i><b>14.1.6</b> Anoxic waters</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="glossary.html"><a href="glossary.html#b"><i class="fa fa-check"></i><b>14.2</b> B</a><ul>
<li class="chapter" data-level="14.2.1" data-path="glossary.html"><a href="glossary.html#benthic"><i class="fa fa-check"></i><b>14.2.1</b> Benthic</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="glossary.html"><a href="glossary.html#c"><i class="fa fa-check"></i><b>14.3</b> C</a><ul>
<li class="chapter" data-level="14.3.1" data-path="glossary.html"><a href="glossary.html#carbon-dioxide"><i class="fa fa-check"></i><b>14.3.1</b> Carbon dioxide</a></li>
<li class="chapter" data-level="14.3.2" data-path="glossary.html"><a href="glossary.html#carbonates"><i class="fa fa-check"></i><b>14.3.2</b> Carbonates</a></li>
<li class="chapter" data-level="14.3.3" data-path="glossary.html"><a href="glossary.html#catabolism"><i class="fa fa-check"></i><b>14.3.3</b> Catabolism</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="glossary.html"><a href="glossary.html#d"><i class="fa fa-check"></i><b>14.4</b> D</a><ul>
<li class="chapter" data-level="14.4.1" data-path="glossary.html"><a href="glossary.html#denitrification"><i class="fa fa-check"></i><b>14.4.1</b> Denitrification</a></li>
<li class="chapter" data-level="14.4.2" data-path="glossary.html"><a href="glossary.html#dihydrogen-sulfide"><i class="fa fa-check"></i><b>14.4.2</b> Dihydrogen sulfide</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="glossary.html"><a href="glossary.html#e"><i class="fa fa-check"></i><b>14.5</b> E</a><ul>
<li class="chapter" data-level="14.5.1" data-path="glossary.html"><a href="glossary.html#EDG-EWG"><i class="fa fa-check"></i><b>14.5.1</b> Electron Donating Group (EDG) and Electron Withdrawing Group (EWG)</a></li>
<li class="chapter" data-level="14.5.2" data-path="glossary.html"><a href="glossary.html#eutrophication"><i class="fa fa-check"></i><b>14.5.2</b> Eutrophication</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="glossary.html"><a href="glossary.html#f"><i class="fa fa-check"></i><b>14.6</b> F</a><ul>
<li class="chapter" data-level="14.6.1" data-path="glossary.html"><a href="glossary.html#fischer-projection"><i class="fa fa-check"></i><b>14.6.1</b> Fischer projection</a></li>
</ul></li>
<li class="chapter" data-level="14.7" data-path="glossary.html"><a href="glossary.html#g"><i class="fa fa-check"></i><b>14.7</b> G</a><ul>
<li class="chapter" data-level="14.7.1" data-path="glossary.html"><a href="glossary.html#greenhouse-gases-ghg"><i class="fa fa-check"></i><b>14.7.1</b> Greenhouse gases <em>(GHG)</em></a></li>
</ul></li>
<li class="chapter" data-level="14.8" data-path="glossary.html"><a href="glossary.html#h"><i class="fa fa-check"></i><b>14.8</b> H</a><ul>
<li class="chapter" data-level="14.8.1" data-path="glossary.html"><a href="glossary.html#haber-bosch-process"><i class="fa fa-check"></i><b>14.8.1</b> Haber-Bosch process</a></li>
<li class="chapter" data-level="14.8.2" data-path="glossary.html"><a href="glossary.html#haworth-projection"><i class="fa fa-check"></i><b>14.8.2</b> Haworth Projection</a></li>
<li class="chapter" data-level="14.8.3" data-path="glossary.html"><a href="glossary.html#H2S"><i class="fa fa-check"></i><b>14.8.3</b> Hydrogen Sulfide</a></li>
</ul></li>
<li class="chapter" data-level="14.9" data-path="glossary.html"><a href="glossary.html#l"><i class="fa fa-check"></i><b>14.9</b> L</a><ul>
<li class="chapter" data-level="14.9.1" data-path="glossary.html"><a href="glossary.html#lithotrophs"><i class="fa fa-check"></i><b>14.9.1</b> Lithotrophs</a></li>
<li class="chapter" data-level="14.9.2" data-path="glossary.html"><a href="glossary.html#limiting-factor"><i class="fa fa-check"></i><b>14.9.2</b> Limiting factor</a></li>
</ul></li>
<li class="chapter" data-level="14.10" data-path="glossary.html"><a href="glossary.html#m"><i class="fa fa-check"></i><b>14.10</b> M</a><ul>
<li class="chapter" data-level="14.10.1" data-path="glossary.html"><a href="glossary.html#methane"><i class="fa fa-check"></i><b>14.10.1</b> Methane</a></li>
<li class="chapter" data-level="14.10.2" data-path="glossary.html"><a href="glossary.html#mineralization"><i class="fa fa-check"></i><b>14.10.2</b> Mineralization</a></li>
</ul></li>
<li class="chapter" data-level="14.11" data-path="glossary.html"><a href="glossary.html#n"><i class="fa fa-check"></i><b>14.11</b> N</a><ul>
<li class="chapter" data-level="14.11.1" data-path="glossary.html"><a href="glossary.html#nitrate"><i class="fa fa-check"></i><b>14.11.1</b> Nitrate</a></li>
<li class="chapter" data-level="14.11.2" data-path="glossary.html"><a href="glossary.html#nitrous-oxide"><i class="fa fa-check"></i><b>14.11.2</b> Nitrous Oxide</a></li>
</ul></li>
<li class="chapter" data-level="14.12" data-path="glossary.html"><a href="glossary.html#o"><i class="fa fa-check"></i><b>14.12</b> O</a><ul>
<li class="chapter" data-level="14.12.1" data-path="glossary.html"><a href="glossary.html#oligotrophication"><i class="fa fa-check"></i><b>14.12.1</b> Oligotrophication</a></li>
<li class="chapter" data-level="14.12.2" data-path="glossary.html"><a href="glossary.html#oxidation"><i class="fa fa-check"></i><b>14.12.2</b> Oxidation</a></li>
<li class="chapter" data-level="14.12.3" data-path="glossary.html"><a href="glossary.html#oxidation-state"><i class="fa fa-check"></i><b>14.12.3</b> Oxidation state</a></li>
</ul></li>
<li class="chapter" data-level="14.13" data-path="glossary.html"><a href="glossary.html#p"><i class="fa fa-check"></i><b>14.13</b> P</a><ul>
<li class="chapter" data-level="14.13.1" data-path="glossary.html"><a href="glossary.html#phosphate"><i class="fa fa-check"></i><b>14.13.1</b> Phosphate</a></li>
</ul></li>
<li class="chapter" data-level="14.14" data-path="glossary.html"><a href="glossary.html#r"><i class="fa fa-check"></i><b>14.14</b> R</a><ul>
<li class="chapter" data-level="14.14.1" data-path="glossary.html"><a href="glossary.html#reactive-nitrogen"><i class="fa fa-check"></i><b>14.14.1</b> Reactive nitrogen</a></li>
<li class="chapter" data-level="14.14.2" data-path="glossary.html"><a href="glossary.html#redox-glossary"><i class="fa fa-check"></i><b>14.14.2</b> Redox</a></li>
<li class="chapter" data-level="14.14.3" data-path="glossary.html"><a href="glossary.html#redox-couple"><i class="fa fa-check"></i><b>14.14.3</b> Redox couple</a></li>
<li class="chapter" data-level="14.14.4" data-path="glossary.html"><a href="glossary.html#half-reactions-glossary"><i class="fa fa-check"></i><b>14.14.4</b> Redox half-reactions</a></li>
<li class="chapter" data-level="14.14.5" data-path="glossary.html"><a href="glossary.html#reduction"><i class="fa fa-check"></i><b>14.14.5</b> Reduction</a></li>
</ul></li>
<li class="chapter" data-level="14.15" data-path="glossary.html"><a href="glossary.html#s"><i class="fa fa-check"></i><b>14.15</b> S</a><ul>
<li class="chapter" data-level="14.15.1" data-path="glossary.html"><a href="glossary.html#skeletal-formula"><i class="fa fa-check"></i><b>14.15.1</b> Skeletal formula</a></li>
<li class="chapter" data-level="14.15.2" data-path="glossary.html"><a href="glossary.html#structural-formula"><i class="fa fa-check"></i><b>14.15.2</b> Structural formula</a></li>
<li class="chapter" data-level="14.15.3" data-path="glossary.html"><a href="glossary.html#sulfate"><i class="fa fa-check"></i><b>14.15.3</b> Sulfate</a></li>
</ul></li>
<li class="chapter" data-level="14.16" data-path="glossary.html"><a href="glossary.html#t"><i class="fa fa-check"></i><b>14.16</b> T</a><ul>
<li class="chapter" data-level="14.16.1" data-path="glossary.html"><a href="glossary.html#trophs"><i class="fa fa-check"></i><b>14.16.1</b> Trophic names</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="appendix-a.html"><a href="appendix-a.html"><i class="fa fa-check"></i><b>A</b> Appendix A</a><ul>
<li class="chapter" data-level="A.1" data-path="appendix-a.html"><a href="appendix-a.html#quick-guide-on-atom-orbitals-and-lewis-dot-structure"><i class="fa fa-check"></i><b>A.1</b> Quick guide on atom orbitals and Lewis dot structure</a><ul>
<li class="chapter" data-level="A.1.1" data-path="appendix-a.html"><a href="appendix-a.html#orbitals"><i class="fa fa-check"></i><b>A.1.1</b> Electron orbitals</a></li>
</ul></li>
<li class="chapter" data-level="A.2" data-path="appendix-a.html"><a href="appendix-a.html#orbitals-hybridization"><i class="fa fa-check"></i><b>A.2</b> Orbitals hybridization</a></li>
<li class="chapter" data-level="A.3" data-path="appendix-a.html"><a href="appendix-a.html#sigma-pi-bonds"><i class="fa fa-check"></i><b>A.3</b> σ and π bonds</a></li>
<li class="chapter" data-level="A.4" data-path="appendix-a.html"><a href="appendix-a.html#sp3"><i class="fa fa-check"></i><b>A.4</b> <em>sp<sup>3</sup></em> hybridization examples</a><ul>
<li class="chapter" data-level="A.4.1" data-path="appendix-a.html"><a href="appendix-a.html#methane-1"><i class="fa fa-check"></i><b>A.4.1</b> Methane</a></li>
<li class="chapter" data-level="A.4.2" data-path="appendix-a.html"><a href="appendix-a.html#the-water-molecule"><i class="fa fa-check"></i><b>A.4.2</b> The water molecule</a></li>
<li class="chapter" data-level="A.4.3" data-path="appendix-a.html"><a href="appendix-a.html#ammonia-and-ammonium"><i class="fa fa-check"></i><b>A.4.3</b> Ammonia and Ammonium</a></li>
<li class="chapter" data-level="A.4.4" data-path="appendix-a.html"><a href="appendix-a.html#sulfate-1"><i class="fa fa-check"></i><b>A.4.4</b> Sulfate</a></li>
<li class="chapter" data-level="A.4.5" data-path="appendix-a.html"><a href="appendix-a.html#PO4"><i class="fa fa-check"></i><b>A.4.5</b> Phosphate</a></li>
</ul></li>
<li class="chapter" data-level="A.5" data-path="appendix-a.html"><a href="appendix-a.html#sp2-hybridization-examples"><i class="fa fa-check"></i><b>A.5</b> <em>sp<sup>2</sup></em> hybridization examples</a><ul>
<li class="chapter" data-level="A.5.1" data-path="appendix-a.html"><a href="appendix-a.html#nitrate-1"><i class="fa fa-check"></i><b>A.5.1</b> Nitrate</a></li>
<li class="chapter" data-level="A.5.2" data-path="appendix-a.html"><a href="appendix-a.html#nitrite"><i class="fa fa-check"></i><b>A.5.2</b> Nitrite</a></li>
</ul></li>
<li class="chapter" data-level="A.6" data-path="appendix-a.html"><a href="appendix-a.html#sp-hybridization-examples"><i class="fa fa-check"></i><b>A.6</b> <em>sp</em> hybridization examples</a><ul>
<li class="chapter" data-level="A.6.1" data-path="appendix-a.html"><a href="appendix-a.html#carbon-dioxide-1"><i class="fa fa-check"></i><b>A.6.1</b> Carbon dioxide</a></li>
<li class="chapter" data-level="A.6.2" data-path="appendix-a.html"><a href="appendix-a.html#dinitrogen"><i class="fa fa-check"></i><b>A.6.2</b> Dinitrogen</a></li>
</ul></li>
<li class="chapter" data-level="A.7" data-path="appendix-a.html"><a href="appendix-a.html#example-of-no-hybridization"><i class="fa fa-check"></i><b>A.7</b> Example of no hybridization</a><ul>
<li class="chapter" data-level="A.7.1" data-path="appendix-a.html"><a href="appendix-a.html#dihydrogen-sulfide-1"><i class="fa fa-check"></i><b>A.7.1</b> Dihydrogen sulfide</a></li>
</ul></li>
<li class="chapter" data-level="A.8" data-path="appendix-a.html"><a href="appendix-a.html#lewis-dot-structures"><i class="fa fa-check"></i><b>A.8</b> Lewis dot structures</a><ul>
<li class="chapter" data-level="A.8.1" data-path="appendix-a.html"><a href="appendix-a.html#valence-electrons-and-octet-rule"><i class="fa fa-check"></i><b>A.8.1</b> Valence electrons and octet rule</a></li>
<li class="chapter" data-level="A.8.2" data-path="appendix-a.html"><a href="appendix-a.html#building-lewis-dot-structures"><i class="fa fa-check"></i><b>A.8.2</b> Building Lewis dot structures</a></li>
</ul></li>
<li class="chapter" data-level="A.9" data-path="appendix-a.html"><a href="appendix-a.html#molecular-orbitals"><i class="fa fa-check"></i><b>A.9</b> Molecular orbitals</a><ul>
<li class="chapter" data-level="A.9.1" data-path="appendix-a.html"><a href="appendix-a.html#binding-and-antibinding-regions"><i class="fa fa-check"></i><b>A.9.1</b> Binding and antibinding regions</a></li>
<li class="chapter" data-level="A.9.2" data-path="appendix-a.html"><a href="appendix-a.html#bonding-and-antibonding-orbitals"><i class="fa fa-check"></i><b>A.9.2</b> Bonding and antibonding orbitals</a></li>
<li class="chapter" data-level="A.9.3" data-path="appendix-a.html"><a href="appendix-a.html#molecular-orbital-diagrams"><i class="fa fa-check"></i><b>A.9.3</b> Molecular orbital diagrams</a></li>
</ul></li>
<li class="chapter" data-level="A.10" data-path="appendix-a.html"><a href="appendix-a.html#exercises-1"><i class="fa fa-check"></i><b>A.10</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="B" data-path="appendix-b-equilibrium-constants-at-25c.html"><a href="appendix-b-equilibrium-constants-at-25c.html"><i class="fa fa-check"></i><b>B</b> Appendix B: Equilibrium Constants at 25°C</a><ul>
<li class="chapter" data-level="B.1" data-path="appendix-b-equilibrium-constants-at-25c.html"><a href="appendix-b-equilibrium-constants-at-25c.html#equilibrium-reactions-in-the-h2o-h2-o2-system"><i class="fa fa-check"></i><b>B.1</b> Equilibrium reactions in the H<sub>2</sub>O-H<sub>2</sub>-O<sub>2</sub> system</a></li>
<li class="chapter" data-level="B.2" data-path="appendix-b-equilibrium-constants-at-25c.html"><a href="appendix-b-equilibrium-constants-at-25c.html#equilibrium-reactions-in-the-co2-h2o-system"><i class="fa fa-check"></i><b>B.2</b> Equilibrium reactions in the CO<sub>2</sub>-H<sub>2</sub>O system</a></li>
<li class="chapter" data-level="B.3" data-path="appendix-b-equilibrium-constants-at-25c.html"><a href="appendix-b-equilibrium-constants-at-25c.html#equilibrium-reactions-for-nitrogen-species"><i class="fa fa-check"></i><b>B.3</b> Equilibrium reactions for nitrogen species</a></li>
<li class="chapter" data-level="B.4" data-path="appendix-b-equilibrium-constants-at-25c.html"><a href="appendix-b-equilibrium-constants-at-25c.html#equilibrium-reactions-for-phosphorus-species"><i class="fa fa-check"></i><b>B.4</b> Equilibrium reactions for phosphorus species</a></li>
<li class="chapter" data-level="B.5" data-path="appendix-b-equilibrium-constants-at-25c.html"><a href="appendix-b-equilibrium-constants-at-25c.html#equilibrium-reactions-for-sulfur-species"><i class="fa fa-check"></i><b>B.5</b> Equilibrium reactions for sulfur species</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Fundamental Hydro-Biogeochemistry for Ecological Engineering and Environmental Sciences</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="introduction-to-hydrographs-chemographs-concentrations-and-loads" class="section level1">
<h1><span class="header-section-number">Chapter 13</span> Introduction to hydrographs, chemographs, concentrations, and loads</h1>
<p>At the end of this chapter, you should be able to:</p>
<ul>
<li>Recognize a hydrograph and name its descriptors</li>
<li>Know how to calculate cumulative flow volumes</li>
<li>Know how to construct flow duration curves and compare them between small and large watersheds</li>
<li>Recognize a chemograph and define its descriptors</li>
<li>Summarize what the arithmetic average and median concentrations are for common pollutants in mostly agricultural watersheds</li>
<li>Know how to calculate cumulative loads at the event and yearly scale</li>
<li>Distinguish between arithmetic and flow weighted concentrations for a variety of common pollutants in mostly agricultural watersheds</li>
<li>Recognize the importance of high flows to the export of pollutants in watersheds</li>
</ul>
<p></br></br></p>
<div id="hydrographs-as-the-basic-hydrologist-tool" class="section level2">
<h2><span class="header-section-number">13.1</span> Hydrographs as the basic hydrologist tool</h2>
<p>In hydrology, we work with time series of flow rates and concentrations, and many of the conclusions we make are based on the calculations of water and nutrient fluxes. The beginning of this paragraph mentions time series. Indeed, in hydrology we no longer measure flow on a continuous basis, but rather at a given frequency.</p>
<p>From the late 1880s to the early 1980s though, hydrographs were, always at the beginning and, in many cases later on, automatically drawn on paper by a scribing pen on a roll of paper. These would move relative to the other as a function of the variable stage of the nearby stream or river, thereby creating a true <strong><em>continuous</em></strong> record of stage variations or a continuous hydrograph. Nowadays, however, the vast majority not to say all of the hydrological data are collected by electronic equipment at a given time interval and logged on memory chips at a given logging interval.</p>
<p>Thanks to hydrological instruments, we have been able to make measurements of river stages continuously or at a near continuous pace, i.e., at a high frequency (hourly or smaller), for nearly 150 years. From this high frequency data, it has been possible to calculate flow rates and obtain a visual representation of typical variations of flow following a rainfall event.</p>
<p>The first example below is an example of what we refer to as a simple hydrograph, which follows a rainfall event, with an initial baseflow, a rapidly rising limb, a flow peak, and a more slowly falling limb.</p>
<p></br></p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1">hydgph&lt;-<span class="kw">read.csv</span>(<span class="dt">file =</span> <span class="st">&quot;hydgph.csv&quot;</span>, <span class="dt">header =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="kw">names</span>(hydgph)=<span class="kw">c</span>(<span class="st">&quot;date&quot;</span>,<span class="st">&quot;Q&quot;</span>,<span class="st">&quot;NO3&quot;</span>)</a>
<a class="sourceLine" id="cb1-3" data-line-number="3">date=<span class="kw">as.POSIXct</span>(hydgph<span class="op">$</span>date, <span class="dt">format =</span> <span class="st">&quot;%Y-%m-%d %H:%M:%S&quot;</span>) <span class="co"># transforms the first column of the file, which are characters into dates that R understands</span></a>
<a class="sourceLine" id="cb1-4" data-line-number="4">Q=hydgph<span class="op">$</span>Q<span class="op">*</span><span class="dv">1000</span> <span class="co"># Puts in the variable Q the flow rates, which are orginally in m³/s to L/s for better visualization</span></a>
<a class="sourceLine" id="cb1-5" data-line-number="5"><span class="kw">par</span>(<span class="dt">mar=</span><span class="kw">c</span>(<span class="fl">4.5</span>,<span class="fl">4.5</span>,<span class="fl">0.5</span>,<span class="fl">0.5</span>))</a>
<a class="sourceLine" id="cb1-6" data-line-number="6">xlimHG=<span class="kw">as.POSIXct</span>(<span class="kw">c</span>(<span class="st">&quot;1999-01-03 00:00:00&quot;</span>,<span class="st">&quot;1999-01-08 00:00:00&quot;</span>));ylimHG=<span class="kw">c</span>(<span class="dv">50</span>,<span class="dv">350</span>) <span class="co"># this defines the plotting ranges for the x and y axes</span></a>
<a class="sourceLine" id="cb1-7" data-line-number="7"><span class="kw">plot</span>(date,Q,<span class="dt">xlab =</span> <span class="st">&quot;date&quot;</span>,<span class="dt">ylab =</span> <span class="st">&quot;Flow rate (L/s)&quot;</span>,<span class="dt">type =</span> <span class="st">&quot;p&quot;</span>,<span class="dt">col=</span><span class="st">&quot;blue&quot;</span>,<span class="dt">xlim=</span>xlimHG,<span class="dt">ylim=</span>ylimHG) <span class="co"># this plots the hydrograph</span></a></code></pre></div>
<p><img src="Textbook_BAE587_files/figure-html/simple-hydrograph-1.png" width="672" /></p>
<p></br></p>
<p>Although the points are disjointed, it is very tempting to add a line between them, as our observations and intuitions tell us that there is a pattern of flow up or down, and in this example, the time interval between consecutive values is 600 seconds or 10 min. And indeed, this is exactly what hydrologists do, we add lines between points as an approximation of what flow must have looked like during the measurement intervals. The same data plotted without the measurement points looks like the figure below, appears <em>continuous</em>, although it is not!</p>
<p></br></p>
<pre><code>## Warning: package &#39;shape&#39; was built under R version 3.6.2</code></pre>
<p><img src="Textbook_BAE587_files/figure-html/hydrograph2-1.png" width="672" /></p>
<p></br></p>
<div id="characteristics-of-a-hydrograph" class="section level3">
<h3><span class="header-section-number">13.1.1</span> Characteristics of a hydrograph</h3>
<p>A hydrograph is characterized by a <strong><em>fast rising limb</em></strong>, and a <strong><em>slower falling limb</em></strong>. This is the typical response of flow following a rainfall event. The time it takes to go from the beginning of what we refer to as <strong><em>an event</em></strong> to the peak is called <strong><em>time of rise</em></strong>. The maximum of the flow rate is referred to as <strong><em>peakflow</em></strong>.</p>
</div>
<div id="actual-hydrograph-over-an-entire-year" class="section level3">
<h3><span class="header-section-number">13.1.2</span> Actual hydrograph over an entire year</h3>
<p>The goal of the first part above was to realize that there is no such thing as <em>continuous data</em>, but that really all data around the world is an assemblage of discontinuous data points. In the case of hydrological data, all points are auto-correlated, and provided that flow be measured frequently enough, then a linear interpolation between consecutive points is just fine.</p>
<p>Now, let us explore what a typical yearly hydrograph of a watershed in a temperate climate where snow does not play a significant role. The conventional acronym for flow rates is the letter <em>Q</em>.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1">data&lt;-<span class="kw">read.csv</span>(<span class="dt">file=</span><span class="st">&quot;sample_1hr_QC_data.csv&quot;</span>,<span class="dt">header =</span> <span class="ot">TRUE</span>) <span class="co">#Reads file into table format</span></a>
<a class="sourceLine" id="cb3-2" data-line-number="2"></a>
<a class="sourceLine" id="cb3-3" data-line-number="3">WSarea&lt;-<span class="fl">24.2</span> <span class="co">#Area of watershed in km2</span></a>
<a class="sourceLine" id="cb3-4" data-line-number="4">WS&lt;-<span class="st">&quot;Maudouve at Saint-Donan, France&quot;</span></a>
<a class="sourceLine" id="cb3-5" data-line-number="5"><span class="kw">names</span>(data)=<span class="kw">c</span>(<span class="st">&quot;datetime&quot;</span>,<span class="st">&quot;Q&quot;</span>,<span class="st">&quot;C&quot;</span>)   <span class="co"># renames the columns in simpler names</span></a>
<a class="sourceLine" id="cb3-6" data-line-number="6">data&lt;-<span class="kw">as.data.frame</span>(data)</a>
<a class="sourceLine" id="cb3-7" data-line-number="7">data<span class="op">$</span>datetime&lt;-<span class="kw">as.POSIXct</span>(<span class="kw">strptime</span>(data<span class="op">$</span>datetime, <span class="st">&quot;%Y-%m-%d %H:%M:%S&quot;</span>)) <span class="co"># transforms characters into date values understood by R</span></a>
<a class="sourceLine" id="cb3-8" data-line-number="8">D&lt;-data<span class="op">$</span>datetime</a>
<a class="sourceLine" id="cb3-9" data-line-number="9">Q&lt;-data<span class="op">$</span>Q   <span class="co">#Defines Q as the flow value (m3/s)</span></a>
<a class="sourceLine" id="cb3-10" data-line-number="10"></a>
<a class="sourceLine" id="cb3-11" data-line-number="11">N=<span class="kw">nrow</span>(data)   <span class="co">#Sets N to the value equal to the number of total rows in the table</span></a>
<a class="sourceLine" id="cb3-12" data-line-number="12"></a>
<a class="sourceLine" id="cb3-13" data-line-number="13"><span class="co"># definition of the x and y axes limits</span></a>
<a class="sourceLine" id="cb3-14" data-line-number="14"></a>
<a class="sourceLine" id="cb3-15" data-line-number="15">startdate&lt;-D[<span class="dv">1</span>]</a>
<a class="sourceLine" id="cb3-16" data-line-number="16">enddate&lt;-D[N]</a>
<a class="sourceLine" id="cb3-17" data-line-number="17">xlim =<span class="st"> </span><span class="kw">as.POSIXct</span>(<span class="kw">c</span>(startdate,enddate))  <span class="co"># this renders the first and last date understandable for plotting purposes</span></a>
<a class="sourceLine" id="cb3-18" data-line-number="18">ylimQ =<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>,<span class="kw">max</span>(Q))           <span class="co"># ylim for flow</span></a>
<a class="sourceLine" id="cb3-19" data-line-number="19">    </a>
<a class="sourceLine" id="cb3-20" data-line-number="20">ScaleF =<span class="st"> </span><span class="fl">1.2</span>                  <span class="co"># scaling factor for size of fonts and other things</span></a>
<a class="sourceLine" id="cb3-21" data-line-number="21">    </a>
<a class="sourceLine" id="cb3-22" data-line-number="22">y1lab&lt;-<span class="kw">expression</span>(<span class="st">&quot;Flow rate (&quot;</span> <span class="op">*</span><span class="st"> </span>m<span class="op">^</span><span class="dv">3</span> <span class="op">*</span><span class="st"> &quot;/s)&quot;</span>)  <span class="co"># defines the label for flow</span></a>
<a class="sourceLine" id="cb3-23" data-line-number="23"></a>
<a class="sourceLine" id="cb3-24" data-line-number="24"><span class="kw">par</span>(<span class="dt">mar=</span><span class="kw">c</span>(<span class="fl">4.5</span>,<span class="fl">4.5</span>,<span class="dv">4</span>,<span class="fl">4.5</span>))     <span class="co"># defines the sizes, in number of lines, for the margins (bottom, left, top, right)</span></a>
<a class="sourceLine" id="cb3-25" data-line-number="25"></a>
<a class="sourceLine" id="cb3-26" data-line-number="26">    ltyp=<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)</a>
<a class="sourceLine" id="cb3-27" data-line-number="27">    </a>
<a class="sourceLine" id="cb3-28" data-line-number="28">    <span class="kw">plot</span>(D,Q,<span class="dt">col=</span><span class="st">&quot;blue&quot;</span>,<span class="dt">type=</span><span class="st">&quot;l&quot;</span>,<span class="dt">cex=</span><span class="fl">0.1</span>,<span class="dt">yaxt=</span><span class="st">&quot;n&quot;</span>,     </a>
<a class="sourceLine" id="cb3-29" data-line-number="29">         <span class="dt">lty=</span>ltyp[<span class="dv">1</span>],<span class="dt">xaxt=</span><span class="st">&quot;n&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;&quot;</span>,<span class="dt">xlim=</span>xlim,<span class="dt">ylim=</span>ylimQ)</a>
<a class="sourceLine" id="cb3-30" data-line-number="30">    <span class="co"># we are taking all the default addition of axis tick marks and numbers out by using xaxt and yaxt = &quot;n&quot;</span></a>
<a class="sourceLine" id="cb3-31" data-line-number="31">    <span class="co"># and setting the axis labels at nothing using xlab = &quot;&quot; and ylab = &quot;&quot;</span></a>
<a class="sourceLine" id="cb3-32" data-line-number="32">    <span class="kw">abline</span>(<span class="dt">h=</span><span class="dv">0</span>)</a>
<a class="sourceLine" id="cb3-33" data-line-number="33">    <span class="kw">abline</span>(<span class="dt">v=</span><span class="kw">seq</span>(startdate, enddate, <span class="dt">by=</span><span class="st">&quot;week&quot;</span>),<span class="dt">col=</span>(<span class="st">&quot;grey&quot;</span>))</a>
<a class="sourceLine" id="cb3-34" data-line-number="34">    <span class="kw">axis.POSIXct</span>(<span class="dv">1</span>, <span class="dt">at=</span><span class="kw">seq</span>(startdate, enddate, <span class="dt">by=</span><span class="st">&quot;month&quot;</span>), <span class="dt">format=</span><span class="st">&quot;%m/%d&quot;</span>,<span class="dt">cex.axis=</span>ScaleF)</a>
<a class="sourceLine" id="cb3-35" data-line-number="35">    <span class="co"># this tells R that we want the X axis ticks and values to be displayed as dates, be added on a monthly basis,</span></a>
<a class="sourceLine" id="cb3-36" data-line-number="36">    <span class="co"># using the month/day format</span></a>
<a class="sourceLine" id="cb3-37" data-line-number="37">    <span class="kw">axis</span>(<span class="dv">2</span>,<span class="dt">cex.axis=</span>ScaleF)</a>
<a class="sourceLine" id="cb3-38" data-line-number="38">    <span class="co"># this tells R that the first Y axis ticks can be displayed  (that function was repressed earlier by &#39;yaxt=&quot;n&quot; &#39;)</span></a>
<a class="sourceLine" id="cb3-39" data-line-number="39">    <span class="kw">par</span>(<span class="dt">new=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb3-40" data-line-number="40">    <span class="co"># this tells R that a new plot has already been opened, in other words you are telling R to keep adding things</span></a>
<a class="sourceLine" id="cb3-41" data-line-number="41">    <span class="co"># on the existing plot</span></a>
<a class="sourceLine" id="cb3-42" data-line-number="42">    </a>
<a class="sourceLine" id="cb3-43" data-line-number="43">    <span class="kw">mtext</span>(<span class="st">&quot;Dates in 1997-1998&quot;</span>,<span class="dt">side=</span><span class="dv">1</span>,<span class="dt">line=</span><span class="dv">3</span>,<span class="dt">cex=</span>ScaleF) <span class="co"># add in the margin the defined labels and title</span></a>
<a class="sourceLine" id="cb3-44" data-line-number="44">    <span class="kw">mtext</span>(y1lab,<span class="dt">side=</span><span class="dv">2</span>,<span class="dt">line=</span><span class="dv">3</span>,<span class="dt">cex=</span>ScaleF)</a>
<a class="sourceLine" id="cb3-45" data-line-number="45">    <span class="kw">mtext</span>(WS,<span class="dt">side=</span><span class="dv">3</span>,<span class="dt">line=</span><span class="fl">1.5</span>,<span class="dt">cex=</span>ScaleF)</a>
<a class="sourceLine" id="cb3-46" data-line-number="46">    </a>
<a class="sourceLine" id="cb3-47" data-line-number="47">    <span class="kw">legend</span>(<span class="st">&quot;topleft&quot;</span>,<span class="kw">c</span>(<span class="st">&quot;Flow&quot;</span>),<span class="dt">lty =</span> <span class="kw">c</span>(<span class="dv">1</span>), <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;blue&quot;</span>))</a></code></pre></div>
<p><img src="Textbook_BAE587_files/figure-html/Q-plot-1.png" width="672" /></p>
<p></br></br></p>
<p>Notice that one can see individual hydrographs characterized for the rapid rise of flow rates, followed by a rapid fall. But they seem to occur <em>on top</em> of a transient minimum flow rate. The latter is called <strong><em>baseflow</em></strong>. It corresponds to the stream water exclusively fed by groundwater. You can see in this example that there is very low baseflow from September 1<sup>st</sup> to the 3<sup>rd</sup> week of October. A large event around that time raises the baseflow to about 250 L/s and this stays almost stable until the end of the third week of December. This is the time when most of the rainfall starts in this part of the world and heavy rainfall last until the middle of January. The baseflow during these 1.5 months rose above 600 L/s. It took about an entire month with nearly no rainfall from the last week of January to the last week of Febraury for baseflow to go down to the pre-December values. Baseflow stays at that general level between the last week of February to the first week of April. Then a series of large rainfall events raise the baseflow back to high levels throughout the month of April. Again, it takes again about one month for baseflow to decrease and then stay stable throughout the month of June. In July and August, even a relative large event at the end of the first week of July does not raise the baseflow level, which steadily disminishes until the beginning of September.</p>
</div>
<div id="calculating-water-fluxes-or-cumulative-flow-volumes" class="section level3">
<h3><span class="header-section-number">13.1.3</span> Calculating water fluxes or cumulative flow volumes</h3>
<p>Flow peaks matter very much for flooding issues and an entire domain of hydrology and statistical hydrology is devoted to calculating and predicting flow peaks generating floods. For water quality purposes, flow volumes matter just as much as flow peaks do. Indeed, the amount or load of pollutants leaving a field or a watershed, or delivered in a receiving water body, depends on the total volume of water, and, on the concentrations.</p>
<p>Flow volumes or cumulative flows, correspond to the cumulative volume of water that has passed at a particular point over a given period. Mathematically, this means that flow volumes correspond to the integral over time of the instantaneous flow rates. or</p>
<p><span class="math display">\[
CumulQ = \int_{}^{period}{Q(t).dt}
\]</span></p>
<p>In practice, because the instantaneous flow rates are discrete in time,</p>
<p><span class="math display">\[
CumulQ = \sum_{i=1}^{n-1}{\frac{(Q_i + Q_{i+1})}{2}}.time \space interval
\]</span></p>
<p>If we zoom on a hypothetical hydrograph named TS (time series), this corresponds to cumulating the area under each trapeze represented below.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mar=</span><span class="kw">c</span>(<span class="fl">4.5</span>,<span class="fl">4.5</span>,<span class="fl">0.5</span>,<span class="fl">0.5</span>))       </a>
<a class="sourceLine" id="cb4-2" data-line-number="2">x&lt;-<span class="dv">1</span><span class="op">:</span><span class="dv">10</span></a>
<a class="sourceLine" id="cb4-3" data-line-number="3">TS&lt;-<span class="dv">25</span><span class="op">-</span>(x<span class="dv">-5</span>)<span class="op">^</span><span class="dv">2</span><span class="op">+</span><span class="dv">2</span>;xlim=<span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">11</span>);ylim=<span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">30</span>)</a>
<a class="sourceLine" id="cb4-4" data-line-number="4"><span class="kw">plot</span>(x,TS,<span class="dt">xlim=</span>xlim,<span class="dt">ylim=</span>ylim)</a>
<a class="sourceLine" id="cb4-5" data-line-number="5">date&lt;-<span class="kw">as.character</span>(date)                 <span class="co"># need to transfer dates back into character to make some operations</span></a>
<a class="sourceLine" id="cb4-6" data-line-number="6">polygx&lt;-<span class="kw">cbind</span>(<span class="kw">head</span>(x,<span class="op">-</span><span class="dv">1</span>),<span class="kw">head</span>(x,<span class="op">-</span><span class="dv">1</span>),x[<span class="op">-</span><span class="dv">1</span>],x[<span class="op">-</span><span class="dv">1</span>],<span class="kw">head</span>(x,<span class="op">-</span><span class="dv">1</span>))         <span class="co"># x values of the polygons</span></a>
<a class="sourceLine" id="cb4-7" data-line-number="7">polygy&lt;-<span class="kw">cbind</span>(<span class="kw">rep</span>(<span class="dv">0</span>,<span class="kw">length</span>(TS)<span class="op">-</span><span class="dv">1</span>),<span class="kw">head</span>(TS,<span class="op">-</span><span class="dv">1</span>),TS[<span class="op">-</span><span class="dv">1</span>],<span class="kw">rep</span>(<span class="dv">0</span>,<span class="kw">length</span>(TS)<span class="op">-</span><span class="dv">1</span>),<span class="kw">rep</span>(<span class="dv">0</span>,<span class="kw">length</span>(TS)<span class="op">-</span><span class="dv">1</span>))   <span class="co"># y values of the polygons</span></a>
<a class="sourceLine" id="cb4-8" data-line-number="8"><span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>(<span class="kw">length</span>(TS)<span class="op">-</span><span class="dv">1</span>)){<span class="kw">polygon</span>((<span class="kw">as.vector</span>(polygx[j,])),<span class="kw">as.vector</span>(polygy[j,]),<span class="dt">col=</span><span class="st">&quot;lightblue&quot;</span>)}</a>
<a class="sourceLine" id="cb4-9" data-line-number="9">date&lt;-<span class="kw">as.POSIXct</span>(date)</a>
<a class="sourceLine" id="cb4-10" data-line-number="10"><span class="kw">par</span>(<span class="dt">new=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb4-11" data-line-number="11"><span class="kw">plot</span>(x,TS,<span class="dt">xlim=</span>xlim,<span class="dt">ylim=</span>ylim)     </a></code></pre></div>
<p><img src="Textbook_BAE587_files/figure-html/instQ-with-trapeze-cumQ-2plots-1.png" width="672" /></p>
<p>One could calculate the cumulative flow by adding over time the area under each trapeze at in the example below. The result of this mock unitless ‘hydrograph’ are displayed underneath.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1">cumTS_inst=<span class="kw">matrix</span>(<span class="dv">0</span>,<span class="dv">10</span>,<span class="dv">1</span>)   <span class="co"># 10 values, the first one being 0 to associate to initial time</span></a>
<a class="sourceLine" id="cb5-2" data-line-number="2"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">9</span>){QQ=(TS[i]<span class="op">+</span>TS[i<span class="op">+</span><span class="dv">1</span>])<span class="op">/</span><span class="dv">2</span>;cumTS_inst[i<span class="op">+</span><span class="dv">1</span>]=cumTS_inst[i]<span class="op">+</span>QQ}</a>
<a class="sourceLine" id="cb5-3" data-line-number="3"><span class="kw">as.vector</span>(cumTS_inst)</a></code></pre></div>
<pre><code>##  [1]   0.0  14.5  35.0  59.5  86.0 112.5 137.0 157.5 172.0 178.5</code></pre>
<p>It turns out that in R, there is a very smart and simple way to calculate cumulative flow, loads, etc. of a time series (TS here) using the code below:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1">time_interval=<span class="dv">1</span></a>
<a class="sourceLine" id="cb7-2" data-line-number="2"><span class="kw">c</span>(<span class="dv">0</span>,(<span class="kw">cumsum</span>(TS[<span class="op">-</span><span class="dv">1</span>])<span class="op">+</span><span class="kw">cumsum</span>(<span class="kw">head</span>(TS,<span class="op">-</span><span class="dv">1</span>)))<span class="op">/</span><span class="dv">2</span>)<span class="op">*</span>time_interval</a></code></pre></div>
<pre><code>##  [1]   0.0  14.5  35.0  59.5  86.0 112.5 137.0 157.5 172.0 178.5</code></pre>
<p>The magic comes the function <code>cumsum()</code> which calculates the cumulative sum of a vector and generates a vector of the same length of the original one:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1"><span class="kw">cumsum</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">2</span>))</a></code></pre></div>
<pre><code>## [1] 1 3 4 6 7 9</code></pre>
<p>and the fact that each trapeze is the average of two rectangles represented below:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mar=</span><span class="kw">c</span>(<span class="fl">4.5</span>,<span class="fl">4.5</span>,<span class="fl">0.5</span>,<span class="fl">0.5</span>))</a>
<a class="sourceLine" id="cb11-2" data-line-number="2"><span class="kw">plot</span>(x,TS,<span class="dt">xlim=</span>xlim,<span class="dt">ylim=</span>ylim)</a>
<a class="sourceLine" id="cb11-3" data-line-number="3">suprectxy=<span class="kw">cbind</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">9</span>,<span class="kw">rep</span>(<span class="dv">0</span>,<span class="dv">9</span>),<span class="dv">2</span><span class="op">:</span><span class="dv">10</span>,TS[<span class="dv">2</span><span class="op">:</span><span class="dv">10</span>])</a>
<a class="sourceLine" id="cb11-4" data-line-number="4">infrectxy=<span class="kw">cbind</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">9</span>,<span class="kw">rep</span>(<span class="dv">0</span>,<span class="dv">9</span>),<span class="dv">2</span><span class="op">:</span><span class="dv">10</span>,TS[<span class="dv">1</span><span class="op">:</span><span class="dv">9</span>])</a>
<a class="sourceLine" id="cb11-5" data-line-number="5"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">9</span>){<span class="kw">rect</span>(infrectxy[i,<span class="dv">1</span>],infrectxy[i,<span class="dv">2</span>],infrectxy[i,<span class="dv">3</span>],infrectxy[i,<span class="dv">4</span>],<span class="dt">col =</span> transpblue)}</a>
<a class="sourceLine" id="cb11-6" data-line-number="6"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">9</span>){<span class="kw">rect</span>(suprectxy[i,<span class="dv">1</span>],suprectxy[i,<span class="dv">2</span>],suprectxy[i,<span class="dv">3</span>],suprectxy[i,<span class="dv">4</span>],<span class="dt">col =</span> transpred)}</a></code></pre></div>
<p><img src="Textbook_BAE587_files/figure-html/mock-TS-combined-rect-plot-fig11-1.png" width="672" /></p>
<p>Let us apply this method to the Maudouve hydrograph plotted earlier. Calculating the cumulative flow corresponds to integrating under the hydrograph curve, as represented by the grey area on the left panel. The corresponding cumulative flow, expressed in mm is plotted on the right side of the plots.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">2</span>));<span class="kw">par</span>(<span class="dt">mar=</span><span class="kw">c</span>(<span class="fl">4.5</span>,<span class="dv">5</span>,<span class="fl">0.5</span>,<span class="fl">0.5</span>))</a>
<a class="sourceLine" id="cb12-2" data-line-number="2">xlim =<span class="st"> </span><span class="kw">as.POSIXct</span>(<span class="kw">c</span>(startdate,enddate))    </a>
<a class="sourceLine" id="cb12-3" data-line-number="3">    n=<span class="kw">c</span>(<span class="dv">2500</span>,<span class="dv">4500</span>,N)</a>
<a class="sourceLine" id="cb12-4" data-line-number="4"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">3</span>){</a>
<a class="sourceLine" id="cb12-5" data-line-number="5">  <span class="kw">plot</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dt">col=</span><span class="st">&quot;blue&quot;</span>,<span class="dt">type=</span><span class="st">&quot;l&quot;</span>,<span class="dt">cex=</span><span class="fl">0.1</span>,<span class="dt">yaxt=</span><span class="st">&quot;n&quot;</span>,     </a>
<a class="sourceLine" id="cb12-6" data-line-number="6">         <span class="dt">lty=</span>ltyp[<span class="dv">1</span>],<span class="dt">xaxt=</span><span class="st">&quot;n&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;&quot;</span>,<span class="dt">xlim=</span>xlim,<span class="dt">ylim=</span>ylimQ)</a>
<a class="sourceLine" id="cb12-7" data-line-number="7">    <span class="kw">abline</span>(<span class="dt">h=</span><span class="dv">0</span>)</a>
<a class="sourceLine" id="cb12-8" data-line-number="8">    <span class="kw">axis.POSIXct</span>(<span class="dv">1</span>, <span class="dt">at=</span><span class="kw">seq</span>(startdate, enddate, <span class="dt">by=</span><span class="st">&quot;month&quot;</span>), <span class="dt">format=</span><span class="st">&quot;%m/%d&quot;</span>,<span class="dt">cex.axis=</span>ScaleF)</a>
<a class="sourceLine" id="cb12-9" data-line-number="9">    <span class="kw">axis</span>(<span class="dv">2</span>,<span class="dt">cex.axis=</span>ScaleF)</a>
<a class="sourceLine" id="cb12-10" data-line-number="10">    <span class="kw">polygon</span>(<span class="kw">c</span>(D[<span class="dv">1</span><span class="op">:</span>n[i]],D[n[i]<span class="op">:</span><span class="dv">1</span>]),<span class="kw">c</span>(Q[<span class="dv">1</span><span class="op">:</span>n[i]],<span class="kw">rep</span>(<span class="dv">0</span>,n[i])),<span class="dt">col=</span><span class="st">&quot;grey&quot;</span>)</a>
<a class="sourceLine" id="cb12-11" data-line-number="11">    <span class="kw">par</span>(<span class="dt">new=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb12-12" data-line-number="12">    <span class="kw">plot</span>(D,Q,<span class="dt">col=</span><span class="st">&quot;blue&quot;</span>,<span class="dt">type=</span><span class="st">&quot;l&quot;</span>,<span class="dt">cex=</span><span class="fl">0.1</span>,<span class="dt">yaxt=</span><span class="st">&quot;n&quot;</span>,     </a>
<a class="sourceLine" id="cb12-13" data-line-number="13">         <span class="dt">lty=</span>ltyp[<span class="dv">1</span>],<span class="dt">xaxt=</span><span class="st">&quot;n&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;&quot;</span>,<span class="dt">xlim=</span>xlim,<span class="dt">ylim=</span>ylimQ)</a>
<a class="sourceLine" id="cb12-14" data-line-number="14">    <span class="kw">mtext</span>(<span class="st">&quot;Dates in 1997-1998&quot;</span>,<span class="dt">side=</span><span class="dv">1</span>,<span class="dt">line=</span><span class="dv">3</span>,<span class="dt">cex=</span>ScaleF) <span class="co"># add in the margin the defined labels and title</span></a>
<a class="sourceLine" id="cb12-15" data-line-number="15">    <span class="kw">mtext</span>(y1lab,<span class="dt">side=</span><span class="dv">2</span>,<span class="dt">line=</span><span class="dv">3</span>,<span class="dt">cex=</span>ScaleF)</a>
<a class="sourceLine" id="cb12-16" data-line-number="16">        </a>
<a class="sourceLine" id="cb12-17" data-line-number="17">cumQ=<span class="kw">c</span>(<span class="dv">0</span>,(<span class="kw">cumsum</span>(Q[<span class="op">-</span><span class="dv">1</span>])<span class="op">+</span><span class="kw">cumsum</span>(<span class="kw">head</span>(Q,<span class="op">-</span><span class="dv">1</span>)))<span class="op">/</span><span class="dv">2</span>)<span class="op">*</span><span class="dv">3600</span><span class="op">/</span>WSarea<span class="op">/</span><span class="dv">1000</span> <span class="co"># calculates in mm the cumulative flow for each time stamp </span></a>
<a class="sourceLine" id="cb12-18" data-line-number="18"></a>
<a class="sourceLine" id="cb12-19" data-line-number="19"></a>
<a class="sourceLine" id="cb12-20" data-line-number="20"><span class="kw">plot</span>(D[<span class="dv">1</span><span class="op">:</span>n[i]],cumQ[<span class="dv">1</span><span class="op">:</span>n[i]],<span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">type=</span><span class="st">&quot;l&quot;</span>,<span class="dt">cex=</span><span class="fl">0.1</span>,<span class="dt">yaxt=</span><span class="st">&quot;n&quot;</span>,     </a>
<a class="sourceLine" id="cb12-21" data-line-number="21">         <span class="dt">lty=</span>ltyp[<span class="dv">1</span>],<span class="dt">xaxt=</span><span class="st">&quot;n&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;&quot;</span>,<span class="dt">xlim=</span>xlim,<span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,cumQ[N]))</a>
<a class="sourceLine" id="cb12-22" data-line-number="22">    <span class="kw">abline</span>(<span class="dt">h=</span><span class="dv">0</span>)</a>
<a class="sourceLine" id="cb12-23" data-line-number="23">    <span class="kw">abline</span>(<span class="dt">h=</span><span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">1000</span>,<span class="dt">by=</span><span class="dv">50</span>),<span class="dt">lty=</span><span class="dv">2</span>,<span class="dt">col=</span><span class="st">&quot;lightgrey&quot;</span>)</a>
<a class="sourceLine" id="cb12-24" data-line-number="24">    <span class="kw">axis.POSIXct</span>(<span class="dv">1</span>, <span class="dt">at=</span><span class="kw">seq</span>(startdate, enddate, <span class="dt">by=</span><span class="st">&quot;month&quot;</span>), <span class="dt">format=</span><span class="st">&quot;%m/%d&quot;</span>,<span class="dt">cex.axis=</span>ScaleF)</a>
<a class="sourceLine" id="cb12-25" data-line-number="25">    <span class="kw">axis</span>(<span class="dv">2</span>,<span class="dt">cex.axis=</span>ScaleF)</a>
<a class="sourceLine" id="cb12-26" data-line-number="26">    <span class="kw">par</span>(<span class="dt">new=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb12-27" data-line-number="27">    <span class="kw">mtext</span>(<span class="st">&quot;Dates in 1997-1998&quot;</span>,<span class="dt">side=</span><span class="dv">1</span>,<span class="dt">line=</span><span class="dv">3</span>,<span class="dt">cex=</span>ScaleF) <span class="co"># add in the margin the defined labels and title</span></a>
<a class="sourceLine" id="cb12-28" data-line-number="28">    <span class="kw">mtext</span>(<span class="st">&quot;Cumulative Flow volume (mm)&quot;</span>,<span class="dt">side=</span><span class="dv">2</span>,<span class="dt">line=</span><span class="dv">3</span>,<span class="dt">cex=</span>ScaleF)</a>
<a class="sourceLine" id="cb12-29" data-line-number="29">}</a></code></pre></div>
<p><img src="Textbook_BAE587_files/figure-html/QCumulQ-1.png" width="672" /></p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1">  <span class="kw">print</span>(<span class="kw">signif</span>(<span class="kw">max</span>(cumQ),<span class="dt">digits =</span> <span class="dv">3</span>)) <span class="co"># displays the final cumulative flow value in m3</span></a></code></pre></div>
<pre><code>## [1] 378</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:Q-cumQ-video"></span>
<iframe src="https://www.youtube.com/embed/9UJR6E23lx0" width="95%" height="400px" data-external="1">
</iframe>
<p class="caption">
Figure 13.1: Video illustrating the calculation of cumulative volume by integrating under a hydrograph. Notice that the two high flow periods in January and April participate in a large proportion of the total cumulative volume
</p>
</div>
<p>Notice that most of the increase of the cumulative flow occurs during the January and April periods described above.</p>
</div>
<div id="evaluating-the-importance-of-rare-high-flow-events-flow-duration-curves" class="section level3">
<h3><span class="header-section-number">13.1.4</span> Evaluating the importance of rare high flow events: flow duration curves</h3>
<div id="sorting-flow-and-load-values" class="section level4">
<h4><span class="header-section-number">13.1.4.1</span> Sorting flow and load values</h4>
<p>Flow occurs permanent streams throughout the year, but with bursts following rainfall events, which are, in most places on earth relatively rare. For example, in North Carolina, it rains about 7% of the time. Most of the flow occurs after these rare occurrences. The idea behind the <strong><em>duration curve</em></strong> concept is to characterize the importance of high flow events in the overall volume of water generated.</p>
<p>Flow duration curves represent the percentage of the total flow that occurred in x% of the time corresponding to the highest flows. The same applies for loads. This might sound a bit murky, but hopefully it will not with the further explanations below. To get there, one first needs to order flow and loads in descending order.
<br/><br/></p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1">QSort=<span class="kw">sort</span>(Q,<span class="dt">decreasing =</span> <span class="ot">TRUE</span>)   <span class="co">#Sorts instantaneous flow rates in descending order</span></a></code></pre></div>
<p><br/><br/></p>
<p>One can also calculate the cumulative flow associated with the sorted instantaneous flow rates as follows:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1">cumQSort&lt;-<span class="kw">c</span>(<span class="dv">0</span>,(<span class="kw">cumsum</span>(QSort[<span class="op">-</span><span class="dv">1</span>])<span class="op">+</span><span class="kw">cumsum</span>(<span class="kw">head</span>(QSort,<span class="op">-</span><span class="dv">1</span>)))<span class="op">/</span><span class="dv">2</span>)<span class="op">*</span><span class="dv">3600</span><span class="op">/</span>WSarea<span class="op">/</span><span class="dv">1000</span></a>
<a class="sourceLine" id="cb16-2" data-line-number="2">cumQSortPerc&lt;-cumQSort<span class="op">/</span><span class="kw">tail</span>(cumQSort,<span class="dv">1</span>)<span class="op">*</span><span class="dv">100</span></a></code></pre></div>
<p>The blue hydrograph from above now becomes:
<br/><br/></p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mar=</span><span class="kw">c</span>(<span class="fl">4.5</span>,<span class="fl">4.5</span>,<span class="dv">1</span>,<span class="dv">1</span>)) </a>
<a class="sourceLine" id="cb17-2" data-line-number="2"><span class="kw">plot</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(QSort),QSort,<span class="dt">col=</span><span class="st">&quot;blue&quot;</span>,<span class="dt">type=</span><span class="st">&quot;l&quot;</span>,<span class="dt">cex=</span><span class="fl">0.1</span>,<span class="dt">yaxt=</span><span class="st">&quot;n&quot;</span>,     </a>
<a class="sourceLine" id="cb17-3" data-line-number="3">         <span class="dt">lty=</span>ltyp[<span class="dv">1</span>],<span class="dt">xaxt=</span><span class="st">&quot;n&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylim=</span>ylimQ)</a>
<a class="sourceLine" id="cb17-4" data-line-number="4"><span class="kw">abline</span>(<span class="dt">h=</span><span class="dv">0</span>)    </a>
<a class="sourceLine" id="cb17-5" data-line-number="5"><span class="kw">axis</span>(<span class="dv">2</span>,<span class="dt">cex.axis=</span>ScaleF)   </a>
<a class="sourceLine" id="cb17-6" data-line-number="6"><span class="kw">mtext</span>(y1lab,<span class="dt">side=</span><span class="dv">2</span>,<span class="dt">line=</span><span class="dv">3</span>,<span class="dt">cex=</span>ScaleF)</a>
<a class="sourceLine" id="cb17-7" data-line-number="7"><span class="kw">mtext</span>(<span class="st">&quot;Cumulative number of flow values&quot;</span>,<span class="dt">side=</span><span class="dv">1</span>,<span class="dt">line=</span><span class="dv">3</span>,<span class="dt">cex=</span>ScaleF)</a>
<a class="sourceLine" id="cb17-8" data-line-number="8"><span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>,<span class="kw">c</span>(<span class="st">&quot;Sorted Flow&quot;</span>),<span class="dt">lty =</span> <span class="kw">c</span>(<span class="dv">1</span>), <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;blue&quot;</span>))</a></code></pre></div>
<p><img src="Textbook_BAE587_files/figure-html/unnamed-chunk-52-1.png" width="672" />
<br/><br/><br/></p>
<p>So now the cumulative flow volume curve corresponding to the highest flow rates as a function, not of time anymore but of the cumulative number of flow values looks like this:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mar=</span><span class="kw">c</span>(<span class="fl">4.5</span>,<span class="fl">5.5</span>,<span class="dv">1</span>,<span class="dv">1</span>)) </a>
<a class="sourceLine" id="cb18-2" data-line-number="2"><span class="kw">plot</span>(cumQSortPerc,<span class="dt">col=</span><span class="st">&quot;blue&quot;</span>,<span class="dt">type=</span><span class="st">&quot;l&quot;</span>,<span class="dt">cex=</span><span class="fl">0.1</span>,<span class="dt">yaxt=</span><span class="st">&quot;n&quot;</span>,     </a>
<a class="sourceLine" id="cb18-3" data-line-number="3">         <span class="dt">lty=</span>ltyp[<span class="dv">1</span>],<span class="dt">xaxt=</span><span class="st">&quot;n&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;&quot;</span>, <span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">100</span>))</a>
<a class="sourceLine" id="cb18-4" data-line-number="4"><span class="kw">abline</span>(<span class="dt">h=</span><span class="dv">0</span>)    </a>
<a class="sourceLine" id="cb18-5" data-line-number="5"><span class="kw">axis</span>(<span class="dv">2</span>,<span class="dt">cex.axis=</span>ScaleF)</a>
<a class="sourceLine" id="cb18-6" data-line-number="6"><span class="kw">mtext</span>(<span class="st">&quot;Cumulative number of flow values&quot;</span>,<span class="dt">side=</span><span class="dv">1</span>,<span class="dt">line=</span><span class="dv">1</span>,<span class="dt">cex=</span>ScaleF)</a>
<a class="sourceLine" id="cb18-7" data-line-number="7"><span class="kw">mtext</span>(<span class="st">&quot;%age of cumulative flow corresponding to</span><span class="ch">\n</span><span class="st"> the highest sorted flow rates &quot;</span>,<span class="dt">side=</span><span class="dv">2</span>,<span class="dt">line=</span><span class="dv">3</span>,<span class="dt">cex=</span>ScaleF)</a></code></pre></div>
<p><img src="Textbook_BAE587_files/figure-html/unnamed-chunk-53-1.png" width="672" /></p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1"> <span class="co"># the \n in the text allows for line break in the title</span></a></code></pre></div>
<p><br/></p>
<p>This corresponds to the integration under the curve of the sorted hydrograph as in:</p>
<p><br/></p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" data-line-number="1"><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">2</span>));<span class="kw">par</span>(<span class="dt">mar=</span><span class="kw">c</span>(<span class="fl">4.5</span>,<span class="dv">5</span>,<span class="fl">0.5</span>,<span class="fl">0.5</span>))</a>
<a class="sourceLine" id="cb20-2" data-line-number="2">xlim =<span class="st"> </span><span class="kw">as.POSIXct</span>(<span class="kw">c</span>(startdate,enddate))    </a>
<a class="sourceLine" id="cb20-3" data-line-number="3">    n=<span class="kw">c</span>(<span class="dv">2500</span>,<span class="dv">4500</span>,N)</a>
<a class="sourceLine" id="cb20-4" data-line-number="4"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">3</span>){</a>
<a class="sourceLine" id="cb20-5" data-line-number="5">  <span class="kw">plot</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dt">col=</span><span class="st">&quot;blue&quot;</span>,<span class="dt">type=</span><span class="st">&quot;l&quot;</span>,<span class="dt">cex=</span><span class="fl">0.1</span>,<span class="dt">yaxt=</span><span class="st">&quot;n&quot;</span>,     </a>
<a class="sourceLine" id="cb20-6" data-line-number="6">         <span class="dt">lty=</span>ltyp[<span class="dv">1</span>],<span class="dt">xaxt=</span><span class="st">&quot;n&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;&quot;</span>,<span class="dt">xlim=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="kw">length</span>(Q)),<span class="dt">ylim=</span>ylimQ)</a>
<a class="sourceLine" id="cb20-7" data-line-number="7">    <span class="kw">abline</span>(<span class="dt">h=</span><span class="dv">0</span>)</a>
<a class="sourceLine" id="cb20-8" data-line-number="8">    <span class="kw">axis</span>(<span class="dv">2</span>,<span class="dt">cex.axis=</span>ScaleF)</a>
<a class="sourceLine" id="cb20-9" data-line-number="9">    <span class="kw">polygon</span>(<span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span>n[i],n[i]<span class="op">:</span><span class="dv">1</span>),<span class="kw">c</span>(QSort[<span class="dv">1</span><span class="op">:</span>n[i]],<span class="kw">rep</span>(<span class="dv">0</span>,n[i])),<span class="dt">col=</span><span class="st">&quot;grey&quot;</span>)</a>
<a class="sourceLine" id="cb20-10" data-line-number="10">    <span class="kw">par</span>(<span class="dt">new=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb20-11" data-line-number="11">    <span class="kw">plot</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(QSort),QSort,<span class="dt">col=</span><span class="st">&quot;blue&quot;</span>,<span class="dt">type=</span><span class="st">&quot;l&quot;</span>,<span class="dt">cex=</span><span class="fl">0.1</span>,<span class="dt">yaxt=</span><span class="st">&quot;n&quot;</span>,     </a>
<a class="sourceLine" id="cb20-12" data-line-number="12">         <span class="dt">lty=</span>ltyp[<span class="dv">1</span>],<span class="dt">xaxt=</span><span class="st">&quot;n&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;&quot;</span>,<span class="dt">xlim=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="kw">length</span>(Q)),<span class="dt">ylim=</span>ylimQ)</a>
<a class="sourceLine" id="cb20-13" data-line-number="13">    <span class="kw">mtext</span>(y1lab,<span class="dt">side=</span><span class="dv">2</span>,<span class="dt">line=</span><span class="dv">3</span>,<span class="dt">cex=</span>ScaleF)</a>
<a class="sourceLine" id="cb20-14" data-line-number="14">        </a>
<a class="sourceLine" id="cb20-15" data-line-number="15"><span class="kw">plot</span>(<span class="dv">1</span><span class="op">:</span>n[i],cumQSort[<span class="dv">1</span><span class="op">:</span>n[i]],<span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">type=</span><span class="st">&quot;l&quot;</span>,<span class="dt">cex=</span><span class="fl">0.1</span>,<span class="dt">yaxt=</span><span class="st">&quot;n&quot;</span>,     </a>
<a class="sourceLine" id="cb20-16" data-line-number="16">         <span class="dt">lty=</span>ltyp[<span class="dv">1</span>],<span class="dt">xaxt=</span><span class="st">&quot;n&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;&quot;</span>,<span class="dt">xlim=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="kw">length</span>(Q)),<span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,cumQ[N]))</a>
<a class="sourceLine" id="cb20-17" data-line-number="17">    <span class="kw">abline</span>(<span class="dt">h=</span><span class="dv">0</span>)</a>
<a class="sourceLine" id="cb20-18" data-line-number="18">    <span class="kw">abline</span>(<span class="dt">h=</span><span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">1000</span>,<span class="dt">by=</span><span class="dv">50</span>),<span class="dt">lty=</span><span class="dv">2</span>,<span class="dt">col=</span><span class="st">&quot;lightgrey&quot;</span>)</a>
<a class="sourceLine" id="cb20-19" data-line-number="19">    <span class="kw">axis</span>(<span class="dv">2</span>,<span class="dt">cex.axis=</span>ScaleF)</a>
<a class="sourceLine" id="cb20-20" data-line-number="20">    <span class="kw">par</span>(<span class="dt">new=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb20-21" data-line-number="21">    <span class="kw">mtext</span>(<span class="st">&quot;Cumulative Flow volume (mm)&quot;</span>,<span class="dt">side=</span><span class="dv">2</span>,<span class="dt">line=</span><span class="dv">3</span>,<span class="dt">cex=</span>ScaleF)</a>
<a class="sourceLine" id="cb20-22" data-line-number="22">}</a></code></pre></div>
<p><img src="Textbook_BAE587_files/figure-html/QCumulQSort-1.png" width="672" /></p>
<p><br/><br/></p>
<p>Notice that the cumulative sorted flow curve does not have the two large increases observed for the months of January and April anymore because all flows are sorted in decreasing order, regardless of when they occurred.</p>
<p>Notice that there is still no unit added for the x axis because I decided that the cumulative number of flow value does not really add a lot to the analysis. However, it becomes very interesting to transform these values in probability of occurrence. Each value has 1/N the probability to occur. We can also calculate the cumulative probability of occurrence of flow values. Flow and load duration curves are thus derived this way.</p>
</div>
</div>
<div id="flow-duration-curves-as-flow-exceedance-curves" class="section level3">
<h3><span class="header-section-number">13.1.5</span> Flow duration curves as flow exceedance curves</h3>
<p>The previous curves give the semi-continuous duration curves. In practice, we like to use discrete values or percentages to express ourselves. In other words, to characterize the importance of high flow in the generation of flow volume in a watershed, we like to say something like “50% of the flow in that watershed occurred in 10% of the time, corresponding to the highest flow”. This provides a way of demonstrating of how relatively flashy the watershed may be, either relatively to other watersheds or to previous years.</p>
<p>The flashiness of a watershed refers to how rapidly flow is altered as a result of storm events/varying conditions. More frequent spikes in flow in response to precipitation events, in which flow increases and decreases more greatly and rapidly, are typically indicative of watersheds with predominant portions of streamflow being influenced by surface runoff, a quicker responding contributor of water to streamflow.</p>
<p>Practically, one can associate to each cumulative sorted discharge value a percentage of the total discharge yielding W<sub>k%</sub> values (W for Water volume) corresponding to the k<sup>th</sup> cumulative probability of the time elapsed, with k being an integer. This corresponds to discretize the continuous curves above to 100 points.</p>
<p>Practically this can be calculated like this:<br />
<br/><br/></p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1">Wk=<span class="kw">quantile</span>(cumQSort,<span class="dt">probs=</span><span class="kw">seq</span>(<span class="fl">0.01</span>,<span class="dv">1</span>,<span class="fl">0.01</span>))<span class="op">/</span><span class="kw">tail</span>(cumQSort,<span class="dv">1</span>) <span class="co">#Calculates and assigns Wk% values to a probability occurring in 1-100% of the total time</span></a></code></pre></div>
<p><br/></p>
<p>and the discretized flow duration curve is illustrated below:</p>
<p><br/><br/><br/></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" data-line-number="1">    xlim=<span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">100</span>);ylim=<span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">100</span>);</a>
<a class="sourceLine" id="cb22-2" data-line-number="2">    <span class="kw">plot</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">100</span>,Wk<span class="op">*</span><span class="dv">100</span>,<span class="dt">xlab=</span><span class="st">&quot;Prob of Occurrence %&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;Mk% &amp; Wk%&quot;</span>,<span class="dt">xlim=</span>xlim,<span class="dt">ylim=</span>ylim,<span class="dt">pch=</span><span class="dv">21</span>,<span class="dt">col=</span><span class="st">&quot;black&quot;</span>,<span class="dt">bg=</span><span class="st">&quot;blue&quot;</span>)</a>
<a class="sourceLine" id="cb22-3" data-line-number="3">    <span class="kw">par</span>(<span class="dt">new=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb22-4" data-line-number="4">  <span class="co">#  plot(1:100,Mk*100,xlab=&quot;Prob of Occurrence %&quot;,ylab=&quot;Mk% &amp; Wk%&quot;,xlim=xlim,ylim=ylim,pch=22,col=&quot;black&quot;,bg=ColElmt)</span></a>
<a class="sourceLine" id="cb22-5" data-line-number="5">  <span class="co">#  par(new=TRUE)</span></a>
<a class="sourceLine" id="cb22-6" data-line-number="6">    <span class="kw">abline</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dt">col=</span><span class="st">&quot;black&quot;</span>,<span class="dt">lty=</span><span class="st">&quot;dashed&quot;</span>,<span class="dt">xlim=</span>xlim,<span class="dt">ylim=</span>ylim)</a>
<a class="sourceLine" id="cb22-7" data-line-number="7">    <span class="kw">par</span>(<span class="dt">new=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb22-8" data-line-number="8">    <span class="kw">legend</span>(<span class="st">&quot;bottomright&quot;</span>,<span class="kw">c</span>(<span class="st">&quot;Cumul Q&quot;</span>,<span class="st">&quot;Cumul NO3 load&quot;</span>),</a>
<a class="sourceLine" id="cb22-9" data-line-number="9">          <span class="dt">pch=</span><span class="kw">c</span>(<span class="dv">19</span>),</a>
<a class="sourceLine" id="cb22-10" data-line-number="10">          <span class="dt">col=</span><span class="kw">c</span>(<span class="st">&quot;blue&quot;</span>),</a>
<a class="sourceLine" id="cb22-11" data-line-number="11">          <span class="dt">bg=</span><span class="st">&quot;white&quot;</span>)</a>
<a class="sourceLine" id="cb22-12" data-line-number="12">    <span class="kw">title</span>(<span class="dt">main=</span><span class="st">&quot;Nitrate Load and flow duration curves&quot;</span>) <span class="co"># the \n in the text allows for line break in the title</span></a></code></pre></div>
<p><img src="Textbook_BAE587_files/figure-html/unnamed-chunk-55-1.png" width="672" /></p>
<p><br/><br/></p>
<p>One can then easily report that, for example, in 10% of the time corresponding to the highest flows, 41% of the flow occurred using this <code>signif(Wk[10]*100,digits = 2)</code>% code. This watershed is thus relatively flashy as about 41% of its total flow volume occurs in 10% of the time.</p>
<p>Now, the interesting part of the curve is what happens for the low probability of occurrence because in this analysis, it corresponds to the highest flow. When one adds several curves on the same graph, it become difficult to distinguish the curves together. One way around that is to use log scale of the same graph using the code below.</p>
<p><br/><br/></p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1">    <span class="co">#Code for plotting the double cumulative plot using the normal distribution probabilities to zoom in on the lower tails</span></a>
<a class="sourceLine" id="cb23-2" data-line-number="2">    v&lt;-<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">10</span>,<span class="dv">25</span>,<span class="dv">50</span>,<span class="dv">75</span>,<span class="dv">90</span>,<span class="dv">95</span>,<span class="dv">97</span>,<span class="dv">98</span>,<span class="dv">99</span>,<span class="dv">100</span>) <span class="co">#v is a set of user defined values of percentages of the total time to be used for calculating and plotting specific corresponding Wk% and Mk% values</span></a>
<a class="sourceLine" id="cb23-3" data-line-number="3">    x&lt;-v<span class="op">/</span><span class="dv">100</span>  <span class="co">#Sets x as values of v in percentages</span></a>
<a class="sourceLine" id="cb23-4" data-line-number="4"><span class="co">#       y&lt;-Mk[v]  #Sets y as the set of Mk% values corresponding with percentages of the total time defined by values in x</span></a>
<a class="sourceLine" id="cb23-5" data-line-number="5">    xx&lt;-<span class="kw">qnorm</span>(x) <span class="co">#qnorm takes a given probability (x values in this case) and returns the corresponding cumulative distribution value (Z-score) based on a normal distribution curve   </span></a>
<a class="sourceLine" id="cb23-6" data-line-number="6"><span class="co">#    yy&lt;-qnorm(y) #Here, qnorm is taking the percentages of the load that occur associated with percentages of the total time defined by values in x and calculating associated Z-scores according to a normal distribution curve</span></a>
<a class="sourceLine" id="cb23-7" data-line-number="7">    yV&lt;-Wk[v] <span class="co">#Sets yV as the set of Wk% values corresponding with percentages of the total time defined by values in x</span></a>
<a class="sourceLine" id="cb23-8" data-line-number="8">    yyV&lt;-<span class="kw">qnorm</span>(yV) <span class="co">#qnorm takes percentages of the flow occurring associated with percentages of the total time defined by x values and assigns Z-score values to each probability based on the normal distribution curve </span></a>
<a class="sourceLine" id="cb23-9" data-line-number="9"><span class="co">#    yy&lt;-cbind(yy,yyV) #Binds both sets of Z-score values corresponding with Mk% (yy) and Wk% (yV)</span></a>
<a class="sourceLine" id="cb23-10" data-line-number="10">    xx&lt;-<span class="kw">cbind</span>(xx,xx) <span class="co">#Binds both sets of Z-scores correspdonding with defined percentages of the total time (They are the same, this is for plotting purposes)</span></a>
<a class="sourceLine" id="cb23-11" data-line-number="11"><span class="co">#    color&lt;-c(ColElmt,&quot;blue&quot;) #Defines the plot colors for yy and yV</span></a>
<a class="sourceLine" id="cb23-12" data-line-number="12">    color&lt;-<span class="kw">c</span>(<span class="st">&quot;blue&quot;</span>) <span class="co">#Defines the plot colors for yy and yV</span></a>
<a class="sourceLine" id="cb23-13" data-line-number="13">        </a>
<a class="sourceLine" id="cb23-14" data-line-number="14"></a>
<a class="sourceLine" id="cb23-15" data-line-number="15">    <span class="kw">plot</span>(xx[,<span class="dv">1</span>],yyV,<span class="dt">xlab=</span><span class="st">&quot;Probability of Occurrence (%)&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;Wk%&quot;</span>,</a>
<a class="sourceLine" id="cb23-16" data-line-number="16">         <span class="dt">type=</span><span class="st">&quot;o&quot;</span>,<span class="dt">xaxt=</span><span class="st">&quot;n&quot;</span>,<span class="dt">yaxt=</span><span class="st">&quot;n&quot;</span>,<span class="dt">xlim=</span><span class="kw">c</span>(<span class="op">-</span><span class="fl">2.5</span>,<span class="fl">2.5</span>),<span class="dt">ylim=</span><span class="kw">c</span>(<span class="op">-</span><span class="fl">2.5</span>,<span class="fl">2.5</span>),<span class="dt">pch=</span><span class="dv">19</span>,<span class="dt">col=</span>color) <span class="co">#Plots yy and yV values as a function of xx values</span></a>
<a class="sourceLine" id="cb23-17" data-line-number="17">    <span class="kw">par</span>(<span class="dt">new=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb23-18" data-line-number="18"></a>
<a class="sourceLine" id="cb23-19" data-line-number="19">    </a>
<a class="sourceLine" id="cb23-20" data-line-number="20">    <span class="kw">axis</span>(<span class="dv">1</span>,<span class="dt">at=</span>xx[,<span class="dv">1</span>],<span class="dt">labels=</span>x<span class="op">*</span><span class="dv">100</span>)</a>
<a class="sourceLine" id="cb23-21" data-line-number="21">    <span class="kw">axis</span>(<span class="dv">2</span>,<span class="dt">at=</span>xx[,<span class="dv">1</span>],<span class="dt">labels=</span>x<span class="op">*</span><span class="dv">100</span>)</a>
<a class="sourceLine" id="cb23-22" data-line-number="22">    <span class="kw">title</span>(<span class="dt">main=</span><span class="st">&quot;Double cumulative probability plot for flow volume&quot;</span>) <span class="co"># the \n in the text allows for line break in the title</span></a>
<a class="sourceLine" id="cb23-23" data-line-number="23">    <span class="kw">abline</span>(<span class="dt">h=</span>xx,<span class="dt">lty=</span><span class="dv">3</span>,<span class="dt">col=</span><span class="st">&quot;grey&quot;</span>) <span class="co">#Plots gridlines</span></a>
<a class="sourceLine" id="cb23-24" data-line-number="24">    <span class="kw">abline</span>(<span class="dt">v=</span>xx,<span class="dt">lty=</span><span class="dv">3</span>,<span class="dt">col=</span><span class="st">&quot;grey&quot;</span>)</a>
<a class="sourceLine" id="cb23-25" data-line-number="25">    <span class="kw">legend</span>(<span class="st">&quot;bottomright&quot;</span>,<span class="kw">c</span>(<span class="st">&quot;Cumul Q&quot;</span>),</a>
<a class="sourceLine" id="cb23-26" data-line-number="26">          <span class="dt">pch=</span><span class="dv">1</span>,</a>
<a class="sourceLine" id="cb23-27" data-line-number="27">          <span class="dt">col=</span>color,</a>
<a class="sourceLine" id="cb23-28" data-line-number="28">          <span class="dt">bg=</span><span class="st">&quot;white&quot;</span>)</a></code></pre></div>
<p><img src="Textbook_BAE587_files/figure-html/unnamed-chunk-56-1.png" width="672" />
<br/><br/><br/></p>
</div>
</div>
<div id="chemographs-and-concentration-levels" class="section level2">
<h2><span class="header-section-number">13.2</span> Chemographs and concentration levels</h2>
<p>With rapid changes in flow during events, concentrations vary just as well. This has remained pretty much hidden to most people until the 1980s because there was no easy way to measure water quality at the pace at which flow rates were measured. Since then instruments have been able to capture concentrations at a pace equal or close to that of flow monitoring.</p>
<p>The curve that plots the variations of concentrations with flow is referred to as a <strong><em>chemograph</em></strong>. The nitrate annual chemograph for the Maudouve watershed presented above is illustrated below.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" data-line-number="1">data&lt;-<span class="kw">read.csv</span>(<span class="dt">file=</span><span class="st">&quot;sample_1hr_QC_data.csv&quot;</span>,<span class="dt">header =</span> <span class="ot">TRUE</span>) <span class="co">#Reads file into table format</span></a>
<a class="sourceLine" id="cb24-2" data-line-number="2"></a>
<a class="sourceLine" id="cb24-3" data-line-number="3">WSarea&lt;-<span class="fl">24.2</span> <span class="co">#Area of watershed in km2</span></a>
<a class="sourceLine" id="cb24-4" data-line-number="4">WS&lt;-<span class="st">&quot;Maudouve at Saint-Donan, France&quot;</span></a>
<a class="sourceLine" id="cb24-5" data-line-number="5"><span class="kw">names</span>(data)=<span class="kw">c</span>(<span class="st">&quot;datetime&quot;</span>,<span class="st">&quot;Q&quot;</span>,<span class="st">&quot;C&quot;</span>)   <span class="co"># renames the columns in simpler names</span></a>
<a class="sourceLine" id="cb24-6" data-line-number="6">data&lt;-<span class="kw">as.data.frame</span>(data)</a>
<a class="sourceLine" id="cb24-7" data-line-number="7">data<span class="op">$</span>datetime&lt;-<span class="kw">as.POSIXct</span>(<span class="kw">strptime</span>(data<span class="op">$</span>datetime, <span class="st">&quot;%Y-%m-%d %H:%M:%S&quot;</span>)) <span class="co"># transforms characters into date values understood by R</span></a>
<a class="sourceLine" id="cb24-8" data-line-number="8">D&lt;-data<span class="op">$</span>datetime</a>
<a class="sourceLine" id="cb24-9" data-line-number="9">Q&lt;-data<span class="op">$</span>Q   <span class="co">#Defines Q as the flow value (m3/s)</span></a>
<a class="sourceLine" id="cb24-10" data-line-number="10">C&lt;-data<span class="op">$</span>C   <span class="co">#Defines C as the Concentration value (mg NO3-N/L)</span></a>
<a class="sourceLine" id="cb24-11" data-line-number="11">L&lt;-Q<span class="op">*</span>C <span class="co"># Calculates the load in grams</span></a>
<a class="sourceLine" id="cb24-12" data-line-number="12">N=<span class="kw">nrow</span>(data)   <span class="co">#Sets N to the value equal to the number of total rows in the table</span></a>
<a class="sourceLine" id="cb24-13" data-line-number="13">startdate&lt;-D[<span class="dv">1</span>]</a>
<a class="sourceLine" id="cb24-14" data-line-number="14">enddate&lt;-D[N]</a>
<a class="sourceLine" id="cb24-15" data-line-number="15"></a>
<a class="sourceLine" id="cb24-16" data-line-number="16"><span class="co"># definition of the x and y axes limits</span></a>
<a class="sourceLine" id="cb24-17" data-line-number="17">xlim =<span class="st"> </span><span class="kw">as.POSIXct</span>(<span class="kw">c</span>(startdate,enddate))  <span class="co"># this renders the first and last date understandable for plotting purposes</span></a>
<a class="sourceLine" id="cb24-18" data-line-number="18">ylimQ =<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>,<span class="kw">max</span>(Q))           <span class="co"># ylim for flow</span></a>
<a class="sourceLine" id="cb24-19" data-line-number="19">ylimC =<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>,<span class="kw">max</span>(C))           <span class="co"># ylim for concentrations</span></a>
<a class="sourceLine" id="cb24-20" data-line-number="20">    </a>
<a class="sourceLine" id="cb24-21" data-line-number="21">ScaleF =<span class="st"> </span><span class="fl">1.2</span>                  <span class="co"># scaling factor for size of fonts and other things</span></a>
<a class="sourceLine" id="cb24-22" data-line-number="22">    </a>
<a class="sourceLine" id="cb24-23" data-line-number="23">y1lab&lt;-<span class="kw">expression</span>(<span class="st">&quot;Flow rate (&quot;</span> <span class="op">*</span><span class="st"> </span>m<span class="op">^</span><span class="dv">3</span> <span class="op">*</span><span class="st"> &quot;/s)&quot;</span>)  <span class="co"># defines the label for flow</span></a>
<a class="sourceLine" id="cb24-24" data-line-number="24">y2lab&lt;-<span class="kw">substitute</span>(<span class="kw">paste</span>(<span class="st">&quot;Nitrate concentration (mg &quot;</span>,NO[x]<span class="op">^</span>{y},<span class="st">&quot;-N)&quot;</span>,<span class="dt">sep=</span><span class="st">&quot;&quot;</span>),<span class="kw">list</span>(<span class="dt">x=</span><span class="dv">3</span>,<span class="dt">y=</span><span class="st">&quot;-&quot;</span>)) <span class="co"># defines the label for concentrations</span></a>
<a class="sourceLine" id="cb24-25" data-line-number="25"></a>
<a class="sourceLine" id="cb24-26" data-line-number="26"><span class="kw">par</span>(<span class="dt">mar=</span><span class="kw">c</span>(<span class="fl">4.5</span>,<span class="fl">4.5</span>,<span class="dv">4</span>,<span class="fl">4.5</span>))     <span class="co"># defines the sizes, in number of lines, for the margins (bottom, left, top, right)</span></a>
<a class="sourceLine" id="cb24-27" data-line-number="27"></a>
<a class="sourceLine" id="cb24-28" data-line-number="28">    ltyp=<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)</a>
<a class="sourceLine" id="cb24-29" data-line-number="29">    </a>
<a class="sourceLine" id="cb24-30" data-line-number="30">    <span class="kw">plot</span>(D,Q,<span class="dt">col=</span><span class="st">&quot;blue&quot;</span>,<span class="dt">type=</span><span class="st">&quot;l&quot;</span>,<span class="dt">cex=</span><span class="fl">0.1</span>,<span class="dt">yaxt=</span><span class="st">&quot;n&quot;</span>,     </a>
<a class="sourceLine" id="cb24-31" data-line-number="31">         <span class="dt">lty=</span>ltyp[<span class="dv">1</span>],<span class="dt">xaxt=</span><span class="st">&quot;n&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;&quot;</span>,<span class="dt">xlim=</span>xlim,<span class="dt">ylim=</span>ylimQ)</a>
<a class="sourceLine" id="cb24-32" data-line-number="32">    <span class="co"># we are taking all the default addition of axis tick marks and numbers out by using xaxt and yaxt = &quot;n&quot;</span></a>
<a class="sourceLine" id="cb24-33" data-line-number="33">    <span class="co"># and setting the axis labels at nothing using xlab = &quot;&quot; and ylab = &quot;&quot;</span></a>
<a class="sourceLine" id="cb24-34" data-line-number="34">    </a>
<a class="sourceLine" id="cb24-35" data-line-number="35">    <span class="kw">abline</span>(<span class="dt">h=</span><span class="dv">0</span>)</a>
<a class="sourceLine" id="cb24-36" data-line-number="36">    <span class="kw">abline</span>(<span class="dt">v=</span><span class="kw">seq</span>(startdate, enddate, <span class="dt">by=</span><span class="st">&quot;week&quot;</span>),<span class="dt">col=</span>(<span class="st">&quot;grey&quot;</span>))</a>
<a class="sourceLine" id="cb24-37" data-line-number="37">    <span class="kw">axis.POSIXct</span>(<span class="dv">1</span>, <span class="dt">at=</span><span class="kw">seq</span>(startdate, enddate, <span class="dt">by=</span><span class="st">&quot;month&quot;</span>), <span class="dt">format=</span><span class="st">&quot;%m/%d&quot;</span>,<span class="dt">cex.axis=</span>ScaleF)</a>
<a class="sourceLine" id="cb24-38" data-line-number="38">    <span class="co"># this tells R that we want the X axis ticks and values to be displayed as dates, be added on a monthly basis,</span></a>
<a class="sourceLine" id="cb24-39" data-line-number="39">    <span class="co"># using the month/day format</span></a>
<a class="sourceLine" id="cb24-40" data-line-number="40">    <span class="kw">axis</span>(<span class="dv">2</span>,<span class="dt">cex.axis=</span>ScaleF)</a>
<a class="sourceLine" id="cb24-41" data-line-number="41">    <span class="co"># this tells R that the first Y axis ticks can be displayed  (that function was repressed earlier by &#39;yaxt=&quot;n&quot; &#39;)</span></a>
<a class="sourceLine" id="cb24-42" data-line-number="42">    <span class="kw">par</span>(<span class="dt">new=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb24-43" data-line-number="43">    <span class="co"># this tells R that a new plot has already been opened, in other words you are telling R to keep adding things</span></a>
<a class="sourceLine" id="cb24-44" data-line-number="44">    <span class="co"># on the existing plot</span></a>
<a class="sourceLine" id="cb24-45" data-line-number="45">    </a>
<a class="sourceLine" id="cb24-46" data-line-number="46">    ColElmt=<span class="st">&quot;deeppink1&quot;</span></a>
<a class="sourceLine" id="cb24-47" data-line-number="47">    <span class="kw">plot</span>(D,C,<span class="dt">col=</span>ColElmt,<span class="dt">type=</span><span class="st">&quot;l&quot;</span>,<span class="dt">cex=</span><span class="fl">0.1</span>,<span class="dt">yaxt=</span><span class="st">&quot;n&quot;</span>,</a>
<a class="sourceLine" id="cb24-48" data-line-number="48">         <span class="dt">lty=</span>ltyp[<span class="dv">1</span>],<span class="dt">xaxt=</span><span class="st">&quot;n&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;&quot;</span>,<span class="dt">xlim=</span>xlim,<span class="dt">ylim=</span>ylimC)</a>
<a class="sourceLine" id="cb24-49" data-line-number="49">    <span class="co"># plots the concentration data</span></a>
<a class="sourceLine" id="cb24-50" data-line-number="50">    <span class="kw">axis</span>(<span class="dv">4</span>,<span class="dt">cex.axis=</span>ScaleF)</a>
<a class="sourceLine" id="cb24-51" data-line-number="51">    <span class="co"># this tells R that the second Y axis ticks can be displayed (that function was repressed earlier by &#39;yaxt=&quot;n&quot; &#39;)</span></a>
<a class="sourceLine" id="cb24-52" data-line-number="52">    <span class="kw">par</span>(<span class="dt">new=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb24-53" data-line-number="53">    </a>
<a class="sourceLine" id="cb24-54" data-line-number="54">    <span class="kw">mtext</span>(<span class="st">&quot;Dates in 1997-1998&quot;</span>,<span class="dt">side=</span><span class="dv">1</span>,<span class="dt">line=</span><span class="dv">3</span>,<span class="dt">cex=</span>ScaleF) <span class="co"># add in the margin the defined labels and title</span></a>
<a class="sourceLine" id="cb24-55" data-line-number="55">    <span class="kw">mtext</span>(y1lab,<span class="dt">side=</span><span class="dv">2</span>,<span class="dt">line=</span><span class="dv">3</span>,<span class="dt">cex=</span>ScaleF)</a>
<a class="sourceLine" id="cb24-56" data-line-number="56">    <span class="kw">mtext</span>(y2lab,<span class="dt">side=</span><span class="dv">4</span>,<span class="dt">line=</span><span class="dv">3</span>,<span class="dt">cex=</span>ScaleF)</a>
<a class="sourceLine" id="cb24-57" data-line-number="57">    <span class="kw">mtext</span>(WS,<span class="dt">side=</span><span class="dv">3</span>,<span class="dt">line=</span><span class="fl">1.5</span>,<span class="dt">cex=</span>ScaleF)</a>
<a class="sourceLine" id="cb24-58" data-line-number="58">    </a>
<a class="sourceLine" id="cb24-59" data-line-number="59">    <span class="kw">legend</span>(<span class="st">&quot;topleft&quot;</span>,<span class="kw">c</span>(<span class="st">&quot;Flow&quot;</span>,<span class="st">&quot;Conc&quot;</span>),<span class="dt">lty =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>), <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;blue&quot;</span>,ColElmt))</a></code></pre></div>
<p><img src="Textbook_BAE587_files/figure-html/unnamed-chunk-57-1.png" width="672" /></p>
<p>Zooming around one event illustrates some of important characteristics of chemographs, which may vary depending on the pollutant of concern.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" data-line-number="1">data&lt;-<span class="kw">read.csv</span>(<span class="dt">file=</span><span class="st">&quot;sample_1hr_QC_data.csv&quot;</span>,<span class="dt">header =</span> <span class="ot">TRUE</span>) <span class="co">#Reads file into table format</span></a>
<a class="sourceLine" id="cb25-2" data-line-number="2"></a>
<a class="sourceLine" id="cb25-3" data-line-number="3">WSarea&lt;-<span class="fl">24.2</span> <span class="co">#Area of watershed in km2</span></a>
<a class="sourceLine" id="cb25-4" data-line-number="4">WS&lt;-<span class="st">&quot;Maudouve at Saint-Donan, France&quot;</span></a>
<a class="sourceLine" id="cb25-5" data-line-number="5"><span class="kw">names</span>(data)=<span class="kw">c</span>(<span class="st">&quot;datetime&quot;</span>,<span class="st">&quot;Q&quot;</span>,<span class="st">&quot;C&quot;</span>)   <span class="co"># renames the columns in simpler names</span></a>
<a class="sourceLine" id="cb25-6" data-line-number="6">data&lt;-<span class="kw">as.data.frame</span>(data)</a>
<a class="sourceLine" id="cb25-7" data-line-number="7">data<span class="op">$</span>datetime&lt;-<span class="kw">as.POSIXct</span>(<span class="kw">strptime</span>(data<span class="op">$</span>datetime, <span class="st">&quot;%Y-%m-%d %H:%M:%S&quot;</span>)) <span class="co"># transforms characters into date values understood by R</span></a>
<a class="sourceLine" id="cb25-8" data-line-number="8">startdate&lt;-<span class="kw">as.POSIXct</span>(<span class="st">&quot;1998-07-04 00:00:00&quot;</span>)</a>
<a class="sourceLine" id="cb25-9" data-line-number="9">enddate&lt;-<span class="kw">as.POSIXct</span>(<span class="st">&quot;1998-07-08 00:00:00&quot;</span>)</a>
<a class="sourceLine" id="cb25-10" data-line-number="10">subdata&lt;-<span class="kw">subset</span>(data,data<span class="op">$</span>datetime<span class="op">&gt;=</span>startdate <span class="op">&amp;</span><span class="st"> </span>data<span class="op">$</span>datetime<span class="op">&lt;=</span>enddate)</a>
<a class="sourceLine" id="cb25-11" data-line-number="11">data&lt;-subdata</a>
<a class="sourceLine" id="cb25-12" data-line-number="12">D&lt;-data<span class="op">$</span>datetime</a>
<a class="sourceLine" id="cb25-13" data-line-number="13">Q&lt;-data<span class="op">$</span>Q   <span class="co">#Defines Q as the flow value (m3/s)</span></a>
<a class="sourceLine" id="cb25-14" data-line-number="14">C&lt;-data<span class="op">$</span>C   <span class="co">#Defines C as the Concentration value (mg NO3-N/L)</span></a>
<a class="sourceLine" id="cb25-15" data-line-number="15">L&lt;-Q<span class="op">*</span>C <span class="co"># Calculates the load in g/s</span></a>
<a class="sourceLine" id="cb25-16" data-line-number="16">N=<span class="kw">nrow</span>(data)   <span class="co">#Sets N to the value equal to the number of total rows in the table</span></a>
<a class="sourceLine" id="cb25-17" data-line-number="17"></a>
<a class="sourceLine" id="cb25-18" data-line-number="18"></a>
<a class="sourceLine" id="cb25-19" data-line-number="19"><span class="co"># definition of the x and y axes limits</span></a>
<a class="sourceLine" id="cb25-20" data-line-number="20">xlim =<span class="st"> </span><span class="kw">as.POSIXct</span>(<span class="kw">c</span>(startdate,enddate))  <span class="co"># this renders the first and last date understandable for plotting purposes</span></a>
<a class="sourceLine" id="cb25-21" data-line-number="21">ylimQ =<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>,<span class="kw">max</span>(Q))           <span class="co"># ylim for flow</span></a>
<a class="sourceLine" id="cb25-22" data-line-number="22">ylimC =<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>,<span class="kw">max</span>(C))           <span class="co"># ylim for concentrations</span></a>
<a class="sourceLine" id="cb25-23" data-line-number="23">    </a>
<a class="sourceLine" id="cb25-24" data-line-number="24">ScaleF =<span class="st"> </span><span class="fl">1.2</span>                  <span class="co"># scaling factor for size of fonts and other things</span></a>
<a class="sourceLine" id="cb25-25" data-line-number="25">    </a>
<a class="sourceLine" id="cb25-26" data-line-number="26">y1lab&lt;-<span class="kw">expression</span>(<span class="st">&quot;Flow rate (&quot;</span> <span class="op">*</span><span class="st"> </span>m<span class="op">^</span><span class="dv">3</span> <span class="op">*</span><span class="st"> &quot;/s)&quot;</span>)  <span class="co"># defines the label for flow</span></a>
<a class="sourceLine" id="cb25-27" data-line-number="27">y2lab&lt;-<span class="kw">substitute</span>(<span class="kw">paste</span>(<span class="st">&quot;Nitrate concentration (mg &quot;</span>,NO[x]<span class="op">^</span>{y},<span class="st">&quot;-N)&quot;</span>,<span class="dt">sep=</span><span class="st">&quot;&quot;</span>),<span class="kw">list</span>(<span class="dt">x=</span><span class="dv">3</span>,<span class="dt">y=</span><span class="st">&quot;-&quot;</span>)) <span class="co"># defines the label for concentrations</span></a>
<a class="sourceLine" id="cb25-28" data-line-number="28"></a>
<a class="sourceLine" id="cb25-29" data-line-number="29"><span class="kw">par</span>(<span class="dt">mar=</span><span class="kw">c</span>(<span class="fl">4.5</span>,<span class="fl">4.5</span>,<span class="dv">4</span>,<span class="fl">4.5</span>))     <span class="co"># defines the sizes, in number of lines, for the margins (bottom, left, top, right)</span></a>
<a class="sourceLine" id="cb25-30" data-line-number="30"></a>
<a class="sourceLine" id="cb25-31" data-line-number="31">    ltyp=<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)</a>
<a class="sourceLine" id="cb25-32" data-line-number="32">    </a>
<a class="sourceLine" id="cb25-33" data-line-number="33">    <span class="kw">plot</span>(D,Q,<span class="dt">col=</span><span class="st">&quot;blue&quot;</span>,<span class="dt">type=</span><span class="st">&quot;l&quot;</span>,<span class="dt">cex=</span><span class="fl">0.1</span>,<span class="dt">yaxt=</span><span class="st">&quot;n&quot;</span>,     </a>
<a class="sourceLine" id="cb25-34" data-line-number="34">         <span class="dt">lty=</span>ltyp[<span class="dv">1</span>],<span class="dt">xaxt=</span><span class="st">&quot;n&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;&quot;</span>,<span class="dt">xlim=</span>xlim,<span class="dt">ylim=</span>ylimQ)</a>
<a class="sourceLine" id="cb25-35" data-line-number="35">    <span class="co"># we are taking all the default addition of axis tick marks and numbers out by using xaxt and yaxt = &quot;n&quot;</span></a>
<a class="sourceLine" id="cb25-36" data-line-number="36">    <span class="co"># and setting the axis labels at nothing using xlab = &quot;&quot; and ylab = &quot;&quot;</span></a>
<a class="sourceLine" id="cb25-37" data-line-number="37">    </a>
<a class="sourceLine" id="cb25-38" data-line-number="38">    <span class="kw">abline</span>(<span class="dt">h=</span><span class="dv">0</span>)</a>
<a class="sourceLine" id="cb25-39" data-line-number="39">    <span class="kw">abline</span>(<span class="dt">v=</span><span class="kw">seq</span>(startdate, enddate, <span class="dt">by=</span><span class="st">&quot;day&quot;</span>),<span class="dt">col=</span>(<span class="st">&quot;grey&quot;</span>))</a>
<a class="sourceLine" id="cb25-40" data-line-number="40">    <span class="kw">axis.POSIXct</span>(<span class="dv">1</span>, <span class="dt">at=</span><span class="kw">seq</span>(startdate, enddate, <span class="dt">by=</span><span class="st">&quot;day&quot;</span>), <span class="dt">format=</span><span class="st">&quot;%m/%d&quot;</span>,<span class="dt">cex.axis=</span>ScaleF)</a>
<a class="sourceLine" id="cb25-41" data-line-number="41">    <span class="co"># this tells R that we want the X axis ticks and values to be displayed as dates, be added on a monthly basis,</span></a>
<a class="sourceLine" id="cb25-42" data-line-number="42">    <span class="co"># using the month/day format</span></a>
<a class="sourceLine" id="cb25-43" data-line-number="43">    <span class="kw">axis</span>(<span class="dv">2</span>,<span class="dt">cex.axis=</span>ScaleF)</a>
<a class="sourceLine" id="cb25-44" data-line-number="44">    <span class="co"># this tells R that the first Y axis ticks can be displayed  (that function was repressed earlier by &#39;yaxt=&quot;n&quot; &#39;)</span></a>
<a class="sourceLine" id="cb25-45" data-line-number="45">    <span class="kw">par</span>(<span class="dt">new=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb25-46" data-line-number="46">    <span class="co"># this tells R that a new plot has already been opened, in other words you are telling R to keep adding things</span></a>
<a class="sourceLine" id="cb25-47" data-line-number="47">    <span class="co"># on the existing plot</span></a>
<a class="sourceLine" id="cb25-48" data-line-number="48">    </a>
<a class="sourceLine" id="cb25-49" data-line-number="49">    ColElmt=<span class="st">&quot;deeppink1&quot;</span></a>
<a class="sourceLine" id="cb25-50" data-line-number="50">    <span class="kw">plot</span>(D,C,<span class="dt">col=</span>ColElmt,<span class="dt">type=</span><span class="st">&quot;l&quot;</span>,<span class="dt">cex=</span><span class="fl">0.1</span>,<span class="dt">yaxt=</span><span class="st">&quot;n&quot;</span>,</a>
<a class="sourceLine" id="cb25-51" data-line-number="51">         <span class="dt">lty=</span>ltyp[<span class="dv">1</span>],<span class="dt">xaxt=</span><span class="st">&quot;n&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;&quot;</span>,<span class="dt">xlim=</span>xlim,<span class="dt">ylim=</span>ylimC)</a>
<a class="sourceLine" id="cb25-52" data-line-number="52">    <span class="co"># plots the concentration data</span></a>
<a class="sourceLine" id="cb25-53" data-line-number="53">    <span class="kw">axis</span>(<span class="dv">4</span>,<span class="dt">cex.axis=</span>ScaleF)</a>
<a class="sourceLine" id="cb25-54" data-line-number="54">    <span class="co"># this tells R that the second Y axis ticks can be displayed (that function was repressed earlier by &#39;yaxt=&quot;n&quot; &#39;)</span></a>
<a class="sourceLine" id="cb25-55" data-line-number="55">    <span class="kw">par</span>(<span class="dt">new=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb25-56" data-line-number="56">    </a>
<a class="sourceLine" id="cb25-57" data-line-number="57">    <span class="kw">mtext</span>(<span class="st">&quot;Dates in 1997-1998&quot;</span>,<span class="dt">side=</span><span class="dv">1</span>,<span class="dt">line=</span><span class="dv">3</span>,<span class="dt">cex=</span>ScaleF) <span class="co"># add in the margin the defined labels and title</span></a>
<a class="sourceLine" id="cb25-58" data-line-number="58">    <span class="kw">mtext</span>(y1lab,<span class="dt">side=</span><span class="dv">2</span>,<span class="dt">line=</span><span class="dv">3</span>,<span class="dt">cex=</span>ScaleF)</a>
<a class="sourceLine" id="cb25-59" data-line-number="59">    <span class="kw">mtext</span>(y2lab,<span class="dt">side=</span><span class="dv">4</span>,<span class="dt">line=</span><span class="dv">3</span>,<span class="dt">cex=</span>ScaleF)</a>
<a class="sourceLine" id="cb25-60" data-line-number="60">    <span class="kw">mtext</span>(WS,<span class="dt">side=</span><span class="dv">3</span>,<span class="dt">line=</span><span class="fl">1.5</span>,<span class="dt">cex=</span>ScaleF)</a>
<a class="sourceLine" id="cb25-61" data-line-number="61">    </a>
<a class="sourceLine" id="cb25-62" data-line-number="62">    <span class="kw">legend</span>(<span class="st">&quot;right&quot;</span>,<span class="kw">c</span>(<span class="st">&quot;Flow&quot;</span>,<span class="st">&quot;Conc&quot;</span>),<span class="dt">lty =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>), <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;blue&quot;</span>,ColElmt))</a></code></pre></div>
<p><img src="Textbook_BAE587_files/figure-html/unnamed-chunk-58-1.png" width="672" /></p>
<p>One can see that the concentration of nitrate in this example is not constant! It varies opposite to flow variations, with the concentrations appearing relatively all the more diluted that flow is high. This is referred to as a <strong><em>dilution effect</em></strong>.</p>
<p>Let us pause for a second and find other indicators of concentration over that the hydrograph period. It is easy to calculate the average or the median concentration over the four days selected here. The arithmetic average concentration can be calculated in the text using <code>signif(mean(C),3)</code>, which yields 14.4 mg N/L. Similarly the median concentration is 14.8 mg N/L. These values are about three times the nitrate concentration values that I ask you to remember for most agricultural water: 5 mg N/L. This is because Brittany in France is a very intensive agricultural area where the denitrification capacities in watersheds are not quite as high as those observed in North Carolina for example.</p>
<p>The level of concentration does give the general pollution level. But more interestingly, it allows to calculate <strong><em>pollutant loads</em></strong>, or the mass of pollutants that flows by a particular station. <strong><em>Instantaneous loads</em></strong> correspond to the mass of pollutant flowing per unit time at a station and its dimensions are [M.T<sup>-1</sup>]. Instantaneous loads for pollutants are the equivalent of flow rates for water. They are calculated as the product of flow by concentrations</p>
<p><span class="math display">\[
L(t) = Q(t).C(t)
\]</span></p>
<p><strong><em>Cumulative loads</em></strong> correspond to the cumulative mass of pollutants that has flowed by a station over a given period of time, and are the equivalent of cumulative flow volume for water.</p>
<p><span class="math display">\[
CumulLoad = \int_{}^{period}{L(t).dt} = \int_{}^{period}{Q(t).C(t).dt}
\]</span></p>
<p>One can calculate the cumulative load of nitrate over the three days of record above using the following code:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" data-line-number="1">cumulLoad&lt;-<span class="kw">c</span>(<span class="dv">0</span>,(<span class="kw">cumsum</span>(L[<span class="op">-</span><span class="dv">1</span>])<span class="op">+</span><span class="kw">cumsum</span>(<span class="kw">head</span>(L,<span class="op">-</span><span class="dv">1</span>)))<span class="op">/</span><span class="dv">2</span>)<span class="op">*</span><span class="dv">3600</span><span class="op">/</span><span class="dv">1000</span></a>
<a class="sourceLine" id="cb26-2" data-line-number="2"><span class="kw">tail</span>(cumulLoad,<span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 839.0834</code></pre>
<p>So this means that over these 4 days, 839 kg N were discharged at that particular station. That is quite a bit!!</p>
<p>In most stations around the world, however, to this day, researchers and water agencies do not have access to the continuous chemograph, but they are still trying to calculate loads. Because most stations do have continuous water flow measurements, one can use this information to calculate loads. Technically, the load calculated above for these 4 days can be calculated by multiplying the flow volume over these four days by the <strong><em>flow-weighted concentration</em></strong> (FWC) value.</p>
<p>FWC in our example can be calculated as:</p>
<p><span class="math display">\[
FWC = \frac{CumulLoad}{CumulQ}
\]</span></p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" data-line-number="1">cumulQ&lt;-<span class="kw">c</span>(<span class="dv">0</span>,(<span class="kw">cumsum</span>(Q[<span class="op">-</span><span class="dv">1</span>])<span class="op">+</span><span class="kw">cumsum</span>(<span class="kw">head</span>(Q,<span class="op">-</span><span class="dv">1</span>)))<span class="op">/</span><span class="dv">2</span>)<span class="op">*</span><span class="dv">3600</span><span class="op">/</span><span class="dv">1000</span></a>
<a class="sourceLine" id="cb28-2" data-line-number="2">FWC&lt;-<span class="kw">tail</span>(cumulLoad,<span class="dv">1</span>)<span class="op">/</span><span class="kw">tail</span>(cumulQ,<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb28-3" data-line-number="3">FWC</a></code></pre></div>
<pre><code>## [1] 12.91443</code></pre>
<p>The FWC in our case here is 12.9 mg N/L, which quite a bit lower than the arithmetic average. This is expected as during the highest flows, the concentrations tend to be diluted.</p>
<p>But in reality, people do not have access to the FWC, so one has to best estimate concentration. There are many different ways, all of which wrong, to estimate these FWC. One is to use the arithmetic average concentration as an estimate. By doing so, one obtains for an estimate of the load over this period using <code>signif(mean(C)*tail(cumulQ,1),3)</code>, i.e., 937 kg, that is 12% more than the actual one.</p>
<p>Let us now look at other datasets, that is data from the Cuyahoga River at Independence in Ohio.</p>
<p><img src="Textbook_BAE587_files/figure-html/unnamed-chunk-61-1.png" width="672" /></p>
<p>We are observing the same <em>dilution effect pattern</em> with nitrate for the Cuyahoga river.</p>
<p>If we look at the TP concentrations, the concentrations increase with flow rates. This is referred to as a <strong><em>concentration effect</em></strong>. In fact the TP concentration peak is a little ahead of the flow peak in this particular case.</p>
<p><img src="Textbook_BAE587_files/figure-html/unnamed-chunk-62-1.png" width="672" /></p>
<pre><code>## [1] 30327.93</code></pre>
<pre><code>## [1] 0.374828</code></pre>
<p>The arithmetic average concentration for TP on these 8 days are 0.335 mg P/L.
The FWC for TP for these 8 days is 0.374828 mg P/L, that is 11% more than the arithmetic average ones. This means that using the arithmetic average concentration to calculate loads will, for nutrients that have a concentration effect, underestimate loads.</p>
<p><strong><em>This chapter is still under construction</em></strong></p>
<p></br></br></br></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="gassolubilitychapter.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="glossary.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/15-hydro-chemographs.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Textbook_BAE587.pdf", "Textbook_BAE587.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
